packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  lefthook: true

catalog:
  "@logtape/logtape": ^2.0.7
  "@types/node": ^25.5.0
  "@typescript/native-preview": 7.0.0-dev.20260421.2
  drizzle-kit: 1.0.0-rc.2
  drizzle-orm: 1.0.0-rc.2
  oxfmt: ^0.48.0
  oxlint: ^1.63.0
  tsdown: ^0.22.0

# delay one day to reduce the risk of installing compromised packages
minimumReleaseAge: 1440
