import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import { join, resolve } from "node:path";
import { defineConfig } from "vite";
import { parseManifest } from "./scripts/manifest.js";

const builtins = [
  ...builtinModules,
  "original-fs",
  "original-fs/promises",
].flatMap((mod) => [mod, `node:${mod}`]);

const jsBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
*/
`;

/** @param {string} pluginId */
function getTestVaultPluginDir(pluginId) {
  return resolve(
    import.meta.dirname,
    "..",
    "..",
    "tests",
    "zt-vault",
    ".obsidian",
    "plugins",
    pluginId,
  );
}

export default defineConfig(({ mode }) => {
  const isProd = mode === "production";
  const isDev = mode === "development";
  const outDir = isProd ? "dist" : "dist-dev";

  return {
    resolve: {
      alias: {
        "@": resolve(import.meta.dirname, "src"),
      },
    },
    define: {
      __DEV__: JSON.stringify(isDev),
      "process.env.NODE_ENV": JSON.stringify(mode),
    },
    build: {
      lib: {
        entry: resolve(import.meta.dirname, "src/zt-main.ts"),
        formats: ["cjs"],
        fileName: () => "main.js",
        cssFileName: "styles",
      },
      outDir,
      emptyOutDir: true,
      sourcemap: isProd ? false : "inline",
      minify: isProd,
      target: "es2022",
      copyPublicDir: false,
      rolldownOptions: {
        external: [
          "obsidian",
          "electron",
          "@electron/remote",
          "@codemirror/autocomplete",
          "@codemirror/collab",
          "@codemirror/commands",
          "@codemirror/language",
          "@codemirror/lint",
          "@codemirror/search",
          "@codemirror/state",
          "@codemirror/view",
          "@lezer/common",
          "@lezer/highlight",
          "@lezer/lr",
          ...builtins,
        ],
        output: {
          banner: jsBanner,
          codeSplitting: false,
        },
      },
    },
    plugins: [obsidianBuildPlugin()],
  };
});

/** @returns {import("vite").Plugin} */
function obsidianBuildPlugin() {
  const packageJsonPath = join(import.meta.dirname, "package.json");
  return {
    name: "obsidian-build",
    buildStart() {
      this.addWatchFile(packageJsonPath);
    },
    async writeBundle(options) {
      const outDir = options.dir ?? "dist";

      const packageJson = JSON.parse(await readFile(packageJsonPath, "utf-8"));
      const manifestJson = parseManifest(packageJson);
      await writeFile(
        join(outDir, "manifest.json"),
        JSON.stringify(manifestJson, null, 2),
      );
      console.log(`Using manifest v${manifestJson.version}`);

      await writeFile(join(outDir, ".hotreload"), "");

      const testVaultPluginDir = getTestVaultPluginDir(manifestJson.id);
      try {
        await mkdir(testVaultPluginDir, { recursive: true });
        const assets = ["main.js", "manifest.json", ".hotreload"];
        await Promise.all(
          assets.map((name) =>
            cp(join(outDir, name), join(testVaultPluginDir, name)),
          ),
        );
        await cp(
          join(outDir, "styles.css"),
          join(testVaultPluginDir, "styles.css"),
        ).catch((err) => {
          if (err.code !== "ENOENT") throw err;
        });
        console.log(`Copied to test vault: ${testVaultPluginDir}`);
      } catch (err) {
        console.warn("Failed to copy to test vault:", err);
      }
    },
  };
}
