import preact from "@preact/preset-vite";
import tailwindcss from "@tailwindcss/vite";
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import { join, resolve } from "node:path";
import { defineConfig } from "vite";
import type { Plugin } from "vite";
import { analyzer, unstableRolldownAdapter } from "vite-bundle-analyzer";

import { obsidianI18n } from "@zotlit/obsidian-i18n/vite";
import { DEV_VAULT_CASE_ENV, getDevVaultDir } from "@zotlit/scripts/dev-vault";
import {
  parseManifest,
  parseMinElectronVersion,
} from "@zotlit/scripts/obsidian-manifest";
import { getWorkspaceRoot } from "@zotlit/scripts/package-roots";

import packageJson from "./package.json" with { type: "json" };
import { pandocFilterVariants } from "./scripts/lua-filter.ts";
import { resolvePandocEnginePin } from "./scripts/pandoc-engine.ts";

import {
  EXCLUDE_MESSAGE_PREFIXES,
  INCLUDE_MESSAGES,
  TARGET_LOCALE_MESSAGE_PREFIXES,
} from "#language-pack-options";

const builtins = [
  ...builtinModules,
  "original-fs",
  "original-fs/promises",
].flatMap((mod) => [mod, `node:${mod}`]);

const jsBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
*/
`;

const workspaceRoot = await getWorkspaceRoot(import.meta.dirname);

// Resolved once per Vite process, so a watch rebuild never re-runs the cross-check.
const pandocEngine = await resolvePandocEnginePin();
console.log(`Pinning Pandoc ${pandocEngine.version}: ${pandocEngine.url}`);

/** `obsidian-vault.ts create` seeds and registers this folder with Obsidian. */
function getDevVaultPluginDir(pluginId: string) {
  return join(
    getDevVaultDir(workspaceRoot, process.env[DEV_VAULT_CASE_ENV]),
    ".obsidian",
    "plugins",
    pluginId,
  );
}

export default defineConfig(({ mode }) => {
  const isProd = mode === "production";
  const isDev = mode === "development";
  const outDir = isProd ? "dist" : "dist-dev";
  const i18nDevServerPort = isDev
    ? parseI18nDevServerPort(process.env.I18N_DEV_SERVER)
    : undefined;

  return {
    resolve: {
      tsconfigPaths: true,
    },
    define: {
      __DEV__: JSON.stringify(isDev),
      __MIN_ELECTRON_VERSION__: JSON.stringify(
        parseMinElectronVersion(packageJson),
      ),
      __PANDOC_ENGINE__: JSON.stringify(pandocEngine),
      "process.env.NODE_ENV": JSON.stringify(mode),
    },
    build: {
      lib: {
        entry: resolve(import.meta.dirname, "src/zt-main.ts"),
        formats: ["cjs"],
        fileName: () => "main.js",
        cssFileName: "styles",
      },
      outDir,
      emptyOutDir: true,
      sourcemap: isProd ? false : "inline",
      minify: isProd,
      target: "es2025",
      copyPublicDir: false,
      rolldownOptions: {
        external: [
          "obsidian",
          "electron",
          "@electron/remote",
          "@codemirror/autocomplete",
          "@codemirror/collab",
          "@codemirror/commands",
          "@codemirror/language",
          "@codemirror/lint",
          "@codemirror/search",
          "@codemirror/state",
          "@codemirror/view",
          "@lezer/common",
          "@lezer/highlight",
          "@lezer/lr",
          ...builtins,
        ],
        output: {
          banner: jsBanner,
          codeSplitting: false,
        },
      },
    },
    plugins: [
      obsidianI18n({
        project: join(workspaceRoot, "project.inlang"),
        output: "src/lib/i18n/generated",
        excludeMessagePrefixes: EXCLUDE_MESSAGE_PREFIXES,
        includeMessages: INCLUDE_MESSAGES,
        targetLocaleMessagePrefixes: TARGET_LOCALE_MESSAGE_PREFIXES,
        servePacks:
          i18nDevServerPort === undefined
            ? undefined
            : { port: i18nDevServerPort },
      }),
      preact(),
      tailwindcss(),
      pandocFilterVariants(),
      obsidianBuildPlugin(),
      process.env.ANALYZE === "true" &&
        unstableRolldownAdapter(
          analyzer({
            analyzerMode: "static",
            fileName: resolve(import.meta.dirname, "bundle-stats"),
            defaultSizes: "stat",
          }),
        ),
    ],
  };
});

/** Opt-in via I18N_DEV_SERVER=true (or a port number); defaults to 9092. */
function parseI18nDevServerPort(value: string | undefined): number | undefined {
  if (!value || value === "false") return undefined;
  const port = Number(value);
  return Number.isInteger(port) && port > 0 ? port : 9092;
}

function obsidianBuildPlugin(): Plugin {
  const packageJsonPath = join(import.meta.dirname, "package.json");
  return {
    name: "obsidian-build",
    buildStart() {
      this.addWatchFile(packageJsonPath);
    },
    async writeBundle(options) {
      const outDir = options.dir ?? "dist";

      const packageJson = JSON.parse(await readFile(packageJsonPath, "utf-8"));
      const manifestJson = parseManifest(packageJson);
      await writeFile(
        join(outDir, "manifest.json"),
        JSON.stringify(manifestJson, null, 2),
      );
      console.log(`Using manifest v${manifestJson.version}`);

      await writeFile(join(outDir, ".hotreload"), "");

      const devVaultPluginDir = getDevVaultPluginDir(manifestJson.id);
      try {
        await mkdir(devVaultPluginDir, { recursive: true });
        const assets = ["main.js", "manifest.json", ".hotreload"];
        await Promise.all(
          assets.map((name) =>
            cp(join(outDir, name), join(devVaultPluginDir, name)),
          ),
        );
        await cp(
          join(outDir, "styles.css"),
          join(devVaultPluginDir, "styles.css"),
        ).catch((err) => {
          if (err.code !== "ENOENT") throw err;
        });
        console.log(`Copied to dev vault: ${devVaultPluginDir}`);
      } catch (err) {
        console.warn("Failed to copy to dev vault:", err);
      }
    },
  };
}
