// Emits the template-data reference page from the committed Template Contract IR.
//
// Prose comes from the contract's doc comments; the page template around it
// lives in `src/lib/template-contract/sections.ts`.
//
// @see docs/adr/0015-template-contract-artifacts-generate-from-ts-types.md

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import { CONTRACT_IR } from "../src/lib/template-contract/contract.ts";
import { renderDocMarkdown } from "../src/lib/template-contract/gfm.ts";
import { buildPageModel } from "../src/lib/template-contract/page-model.ts";
import type {
  PageSection,
  SectionValue,
} from "../src/lib/template-contract/page-model.ts";

const PAGE = join("content", "docs", "reference", "templates", "data.mdx");

const BANNER = `{/* Generated by scripts/generate-template-data.ts from the @zotlit/db template contract - DO NOT EDIT. */}
{/* Edit the doc comments on the \`zt\` types under packages/db/src/lib/context/, regenerate the contract, then run \`pnpm --filter @zotlit/docs generate:template-data\`. */}`;

const FRONTMATTER = `---
title: "Template data"
description: "Every property available on the zt variable, organized by template type."
---`;

const IMPORTS = `import { Card, Cards } from "fumadocs-ui/components/card";

import { Callout } from "@/components/callout";
import { ContractTable } from "@/components/contract-table";`;

const INTRO = `This page lists every property available on \`zt\` in each template type. Use the [Template Data Explorer](/docs/how-to/explore-template-data) against your own library to discover values interactively.`;

const model = buildPageModel(CONTRACT_IR);

const page = renderPage(model.sections);
assertNoUnresolvedLinks(page);
await writeFile(PAGE, page);

for (const warning of model.warnings) console.warn(`Undocumented: ${warning}`);
console.log(
  `Template data page: ${model.sections.length} sections from contract v${CONTRACT_IR.contractVersion}${
    model.warnings.length > 0
      ? ` (${model.warnings.length} undocumented members)`
      : ""
  }.`,
);

function renderPage(sections: readonly PageSection[]): string {
  return `${[FRONTMATTER, BANNER, IMPORTS, INTRO, ...sections.map(renderSection)].join("\n\n")}\n`;
}

function renderSection(section: PageSection): string {
  const blocks = [
    `${"#".repeat(section.level)} ${section.title} [#${section.id}]`,
    ...renderDocMarkdown(section.description, assertPlainText),
    section.lead,
    section.values.length > 0 ? renderValues(section.values) : undefined,
    section.tables.length > 0 || section.itemTypes.length > 0
      ? `<ContractTable section="${section.id}" />`
      : undefined,
    section.include && `<include>${section.include}</include>`,
  ];
  return blocks.filter((block) => block !== undefined).join("\n\n");
}

/** A union of string literals has no properties, so it renders as its options. */
function renderValues(values: readonly SectionValue[]): string {
  return values
    .map(({ value, description }) => {
      const doc = renderDocMarkdown(description, assertPlainText).join(" ");
      return `- \`"${value}"\`${doc ? `: ${doc}` : ""}`;
    })
    .join("\n");
}

/** MDX reads `{` and `<` as expression and element openers, so prose keeps them inside code spans. */
function assertPlainText(text: string): string {
  const opener = /[{}<]/.exec(text);
  if (opener) {
    throw new Error(
      `Doc comment prose carries the MDX opener ${opener[0]} outside a code span: ${text}`,
    );
  }
  return text;
}

/**
 * A link tag reaching the page means the resolver missed it — the reader would
 * see raw JSDoc syntax, so fail instead of emitting it.
 */
function assertNoUnresolvedLinks(page: string): void {
  if (page.includes("{@link")) {
    throw new Error("Emitted page carries an unresolved {@link} tag");
  }
}
