// Emits the template-data reference page from the committed Template Contract IR.
//
// The deploy pipeline excludes `@zotlit/db`, so the IR is copied into this app
// and the page, the table component, and the tests all read the copy. Prose comes
// from the contract's doc comments; the page template around it lives in
// `lib/template-contract/sections.ts`.
//
// @see docs/adr/0015-template-contract-artifacts-generate-from-ts-types.md

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import { type ContractIR } from "../lib/template-contract/ir.ts";
import {
  buildPageModel,
  type Doc,
  type PageSection,
  type SectionValue,
} from "../lib/template-contract/page-model.ts";

const SOURCE_IR = join(
  "..",
  "..",
  "packages",
  "db",
  "src",
  "contract",
  "generated",
  "ir.json",
);
const IR_COPY = join("lib", "template-contract", "generated", "ir.json");
const PAGE = join("content", "docs", "reference", "templates", "data.mdx");

const BANNER = `{/* Generated by scripts/generate-template-data.ts from the @zotlit/db template contract - DO NOT EDIT. */}
{/* Edit the doc comments on the \`zt\` types under packages/db/src/lib/context/, regenerate the contract, then run \`pnpm --filter @zotlit/docs generate:template-data\`. */}`;

const FRONTMATTER = `---
title: "Template data"
description: "Every property available on the zt variable, organized by template type."
---`;

const IMPORTS = `import { Callout } from "fumadocs-ui/components/callout";
import { Card, Cards } from "fumadocs-ui/components/card";

import { ContractTable } from "@/components/contract-table";`;

const INTRO = `This page lists every property available on \`zt\` in each template type. Use the [Template Data Explorer](/docs/how-to/explore-template-data) against your own library to discover values interactively.`;

const source = await readFile(SOURCE_IR, "utf8");
const ir = JSON.parse(source) as ContractIR;
const model = buildPageModel(ir);

await mkdir(dirname(IR_COPY), { recursive: true });
await writeFile(IR_COPY, source);

const page = renderPage(model.sections);
assertNoUnresolvedLinks(page);
await writeFile(PAGE, page);

for (const warning of model.warnings) console.warn(`Undocumented: ${warning}`);
console.log(
  `Template data page: ${model.sections.length} sections from contract v${ir.contractVersion}${
    model.warnings.length > 0
      ? ` (${model.warnings.length} undocumented members)`
      : ""
  }.`,
);

function renderPage(sections: readonly PageSection[]): string {
  return `${[FRONTMATTER, BANNER, IMPORTS, INTRO, ...sections.map(renderSection)].join("\n\n")}\n`;
}

function renderSection(section: PageSection): string {
  const blocks = [
    `${"#".repeat(section.level)} ${section.title} [#${section.id}]`,
    ...renderDoc(section.description),
    section.lead,
    section.values.length > 0 ? renderValues(section.values) : undefined,
    section.tables.length > 0 || section.itemTypes.length > 0
      ? `<ContractTable section="${section.id}" />`
      : undefined,
    section.include && `<include>${section.include}</include>`,
  ];
  return blocks.filter((block) => block !== undefined).join("\n\n");
}

/** A union of string literals has no properties, so it renders as its options. */
function renderValues(values: readonly SectionValue[]): string {
  return values
    .map(({ value, description }) => {
      const doc = renderDoc(description).join(" ");
      return `- \`"${value}"\`${doc ? `: ${doc}` : ""}`;
    })
    .join("\n");
}

/** One Markdown paragraph per normalized paragraph. */
function renderDoc(doc: Doc): string[] {
  return doc.map((paragraph) =>
    paragraph
      .map((node) => {
        switch (node.kind) {
          case "text":
            return assertPlainText(node.value);
          case "code":
            return `\`${node.value}\``;
          case "link":
            return `[${node.code ? `\`${node.text}\`` : node.text}](${node.href})`;
        }
      })
      .join(""),
  );
}

/** MDX reads `{` and `<` as expression and element openers, so prose keeps them inside code spans. */
function assertPlainText(text: string): string {
  const opener = /[{}<]/.exec(text);
  if (opener) {
    throw new Error(
      `Doc comment prose carries the MDX opener ${opener[0]} outside a code span: ${text}`,
    );
  }
  return text;
}

/**
 * A link tag reaching the page means the resolver missed it — the reader would
 * see raw JSDoc syntax, so fail instead of emitting it.
 */
function assertNoUnresolvedLinks(page: string): void {
  if (page.includes("{@link")) {
    throw new Error("Emitted page carries an unresolved {@link} tag");
  }
}
