// GENERATED by scripts/vite-fluent-plugin.ts — DO NOT EDIT.
// Source of truth: locale/*.ftl

export type FluentMessageId =
  | "zotlit-prefs-log-level-debug"
  | "zotlit-prefs-log-level-error"
  | "zotlit-prefs-log-level-fatal"
  | "zotlit-prefs-log-level-info"
  | "zotlit-prefs-log-level-trace"
  | "zotlit-prefs-log-level-warning"
  | "zotlit-prefs-logging-level"
  | "zotlit-prefs-logging-section"
  | "zotlit-prefs-notify-enable"
  | "zotlit-prefs-notify-section"
  | "zotlit-prefs-notify-url"
  | "zotlit-prefs-pane-label";
