// GENERATED by scripts/vite-fluent-plugin.ts — DO NOT EDIT.
// Source of truth: locale/*.ftl

export type FluentMessageId =
  | "zotlit-batch-update-failed-message"
  | "zotlit-batch-update-failed-title"
  | "zotlit-batch-update-sending-title"
  | "zotlit-batch-update-sent-message"
  | "zotlit-batch-update-sent-title"
  | "zotlit-batch-update-server-needed-message"
  | "zotlit-batch-update-server-needed-title"
  | "zotlit-menu-item-open"
  | "zotlit-menu-item-update"
  | "zotlit-menu-item-update-metadata"
  | "zotlit-menu-reader-annot-merge"
  | "zotlit-menu-reader-page-open"
  | "zotlit-prefs-log-level-debug"
  | "zotlit-prefs-log-level-error"
  | "zotlit-prefs-log-level-fatal"
  | "zotlit-prefs-log-level-info"
  | "zotlit-prefs-log-level-trace"
  | "zotlit-prefs-log-level-warning"
  | "zotlit-prefs-logging-level"
  | "zotlit-prefs-logging-section"
  | "zotlit-prefs-notify-enable"
  | "zotlit-prefs-notify-section"
  | "zotlit-prefs-notify-url"
  | "zotlit-prefs-pane-label";
