// GENERATED by scripts/vite-prefs-plugin.ts — DO NOT EDIT.
// Source of truth: addon/prefs.js

export type PluginPrefKey =
  | "extensions.zotlit.log.console-level"
  | "extensions.zotlit.notify"
  | "extensions.zotlit.notify-url";
