import { regex } from "arkregex";
import { readFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { prerelease, rcompare, valid } from "semver";
import { $ } from "zx";

import {
  hasTargetNewPageAvailability,
  hasAvailabilityDeclaration,
  isReviewedForTarget,
  stripAvailabilityLines,
} from "./mdx-frontmatter.ts";

const DOCS_CONTENT_DIR = "apps/docs/content/docs";
const MAX_DIFF_LINES = 60;

/**
 * Pages generated by a script, keyed by path relative to the workspace
 * root. Their content tracks their generator's source, not a human edit —
 * `introduced`/`updated` review is meaningless for them, so they never
 * surface as a scan candidate (see `apps/docs/AGENTS.md`).
 */
const GENERATED_DOCS_PAGES = new Set([
  "apps/docs/content/docs/reference/templates/data.mdx",
]);

export type DocsAvailabilityCandidateKind = "new" | "moved" | "changed";

export interface DocsAvailabilityCandidate {
  kind: DocsAvailabilityCandidateKind;
  /** Path relative to the workspace root. */
  path: string;
  /** Set only for `moved`: the path this page had at the baseline tag. */
  previousPath?: string;
  /** Unified diff against the baseline tag — empty for `new` (nothing to compare). */
  diff: string;
}

export interface DocsAvailabilityScan {
  candidates: readonly DocsAvailabilityCandidate[];
  sectionIndexes: readonly string[];
  skipped: number;
}

const STATUS_LINE = regex("^(?<status>[AMD])\t(?<path>.+)$");
const RENAME_LINE = regex(
  "^R(?<similarity>\\d+)\t(?<oldPath>[^\t]+)\t(?<newPath>.+)$",
);

function isDocsPage(path: string): boolean {
  return (
    path.endsWith(".mdx") &&
    basename(path) !== "index.mdx" &&
    !basename(path).startsWith("_") &&
    !GENERATED_DOCS_PAGES.has(path)
  );
}

/** Highest valid, non-prerelease git tag in the repo — the previous Stable Release Line. */
export async function findPreviousStableTag(
  cwd: string,
): Promise<string | null> {
  const { stdout } = await $({ cwd })`git tag --list`;
  const tags = stdout
    .split("\n")
    .map((line) => line.trim())
    .filter((tag) => valid(tag) !== null && prerelease(tag) === null);
  if (tags.length === 0) return null;
  return tags.sort(rcompare)[0] ?? null;
}

async function readBlobAtTag(
  cwd: string,
  tag: string,
  path: string,
): Promise<string> {
  const { stdout } = await $({ cwd })`git show ${`${tag}:${path}`}`;
  return stdout;
}

/**
 * Availability fields do not count as content, and a page already assigned
 * to the target line does not return to review on a repeat run.
 */
async function shouldReview(
  cwd: string,
  {
    baselineTag,
    baselinePath,
    currentPath,
    targetVersion,
  }: {
    baselineTag: string;
    baselinePath: string;
    currentPath: string;
    targetVersion: string;
  },
): Promise<boolean> {
  const [before, after] = await Promise.all([
    readBlobAtTag(cwd, baselineTag, baselinePath),
    readFile(join(cwd, currentPath), "utf-8"),
  ]);
  if (stripAvailabilityLines(before) === stripAvailabilityLines(after)) {
    return false;
  }
  return !isReviewedForTarget(after, targetVersion);
}

async function diffPage(
  cwd: string,
  baselineTag: string,
  {
    path,
    previousPath,
  }: {
    path: string;
    previousPath?: string;
  },
): Promise<string> {
  const paths = previousPath === undefined ? [path] : [previousPath, path];
  const { stdout } = await $({
    cwd,
  })`git diff -M ${baselineTag} HEAD -- ${paths}`;
  const lines = stdout.split("\n");
  if (lines.length <= MAX_DIFF_LINES) return stdout;
  const hidden = lines.length - MAX_DIFF_LINES;
  const command = `git diff -M ${shellQuote(baselineTag)} HEAD -- ${paths.map(shellQuote).join(" ")}`;
  return `${lines.slice(0, MAX_DIFF_LINES).join("\n")}\n… ${hidden} more lines — see \`${command}\``;
}

/**
 * Diff `content/docs/**\/*.mdx` between `baselineTag` and `HEAD`, classify
 * each touched page, and skip pages already reviewed within this release
 * cycle.
 */
export async function scanDocsAvailability({
  cwd,
  baselineTag,
  targetVersion,
}: {
  cwd: string;
  baselineTag: string;
  targetVersion: string;
}): Promise<DocsAvailabilityScan> {
  const { stdout } = await $({
    cwd,
  })`git diff -M --name-status ${baselineTag} HEAD -- ${DOCS_CONTENT_DIR}`;

  const candidates: DocsAvailabilityCandidate[] = [];
  let skipped = 0;

  for (const line of stdout.split("\n").filter(Boolean)) {
    const rename = RENAME_LINE.exec(line);
    if (rename) {
      const { similarity, oldPath, newPath } = rename.groups;
      if (!isDocsPage(newPath)) {
        skipped += 1;
        continue;
      }
      // 100% similarity: a pure move, content unchanged. `introduced`/
      // `updated` moved with the file's frontmatter — nothing to review.
      if (Number(similarity) >= 100) {
        skipped += 1;
        continue;
      }
      const review = await shouldReview(cwd, {
        baselineTag,
        baselinePath: oldPath,
        currentPath: newPath,
        targetVersion,
      });
      if (!review) {
        skipped += 1;
        continue;
      }
      candidates.push({
        kind: "moved",
        path: newPath,
        previousPath: oldPath,
        diff: await diffPage(cwd, baselineTag, {
          path: newPath,
          previousPath: oldPath,
        }),
      });
      continue;
    }

    const status = STATUS_LINE.exec(line);
    if (!status) continue;
    const { path } = status.groups;
    if (!isDocsPage(path)) {
      skipped += 1;
      continue;
    }

    if (status.groups.status === "A") {
      const current = await readFile(join(cwd, path), "utf-8");
      if (hasTargetNewPageAvailability(current, targetVersion)) {
        skipped += 1;
      } else {
        candidates.push({ kind: "new", path, diff: "" });
      }
    } else if (status.groups.status === "M") {
      const review = await shouldReview(cwd, {
        baselineTag,
        baselinePath: path,
        currentPath: path,
        targetVersion,
      });
      if (!review) {
        skipped += 1;
        continue;
      }
      candidates.push({
        kind: "changed",
        path,
        diff: await diffPage(cwd, baselineTag, { path }),
      });
    } else {
      skipped += 1;
    }
  }

  const { stdout: trackedFiles } = await $({
    cwd,
  })`git ls-files -- ${DOCS_CONTENT_DIR}`;
  const sectionIndexes: string[] = [];
  for (const path of trackedFiles.split("\n").filter(Boolean)) {
    if (!path.endsWith(".mdx") || basename(path) !== "index.mdx") continue;
    const content = await readFile(join(cwd, path), "utf-8");
    if (hasAvailabilityDeclaration(content)) sectionIndexes.push(path);
  }

  candidates.sort((left, right) => left.path.localeCompare(right.path));
  sectionIndexes.sort();
  return { candidates, sectionIndexes, skipped };
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}
