import type { ItemQueryRequest } from "./request";

/** Every Annotation scenario request is checked against the forced scan. */
export const ANNOTATION_SCENARIO_QUERIES: readonly Omit<
  ItemQueryRequest,
  "libraries"
>[] = [
  { fields: ["item.creators[].fullName", "tags[]", "position.rects[][]"] },
  {},
  { fields: [], limit: 2 },
  { filter: '["ART2FULL", "ART2FULLg4815"].contains(item.indexedKey)' },
  { filter: '["PDF2LIVE", "PDF2GRUPg4815"].contains(attachment.indexedKey)' },
  {
    filter:
      'item.indexedKey == "ART2FULL" && attachment.indexedKey == "PDF2LIVE" && type == "image"',
  },
  ...[
    'indexedKey == "ANN2HGHT"',
    '"ANN2GRUPg4815" == indexedKey',
    '["ANN2HGHT", "ANN2GRUPg4815"].contains(indexedKey)',
    'item.indexedKey == "ART2FULL"',
    'item.indexedKey == "ART2FULLg4815"',
    'attachment.indexedKey == "PDF2LIVE"',
    'attachment.indexedKey == "PDF2GRUPg4815"',
    '["PDF2LIVE", "bad"].contains(attachment.indexedKey)',
    'indexedKey == "bad"',
    'item.indexedKey == "ART2FULLg999" || type == "image"',
    '!(attachment.indexedKey == "PDF2LIVE")',
    'library == "personal"',
    'library != "personal"',
    'library == "group:4815"',
    'tags == "figure"',
    'item.date.year == "2014"',
    'tags != "figure"',
    'type == "highlight"',
    'type == "underline"',
    'type == "ink"',
    'type == "text"',
    'type == "note"',
    'type == "image"',
    'type == "unknown"',
    'tags.contains("method")',
    'tags.contains("missing")',
    'color == "yellow"',
    'color == "#ffd400"',
    'color == "orange"',
    'color == "#123456"',
    '"yellow" == color',
    'color != "yellow"',
    'colorName == "yellow"',
    'type == "image" && item.title.contains("Exact")',
    'type == "image" || pageIndex == 0',
    'type == "image" || tags.contains("method")',
    '!(type == "image")',
    'item.key == "ART2FULL"',
    'item.title == "Exact Matching in Literature Review"',
    'item.volume == "12"',
    'item.volume == "012"',
    'item.tags.contains("methods")',
    'item.collections.contains("Thesis/Methods")',
    'item.collections.within("Thesis")',
    "item.date.year == 2020",
    "item.dateModified.year == 2024",
    "dateModified.year == 2024",
    'item.custom["review.status"] == "done"',
    'item.mood == "calm"',
    'item.custom["absent"] == null',
    'item.creators.contains("Ada Lovelace")',
    "hasExcerptImage",
    "pageIndex >= 0 && pageIndex < 3",
    'item.title == "missing" || type == "ink"',
    'item.tags.contains("methods") && tags.contains("method")',
  ].map((filter) => ({
    filter,
    fields: [
      "type",
      "color",
      "item.title",
      'item.custom["review.status"]',
      "item.tags",
      "item.date",
    ],
  })),
  ...[
    "dateAdded",
    "dateModified",
    "type",
    "color",
    "pageIndex",
    "sortIndex",
    "item.title",
    "item.date",
    "item.dateModified",
  ].flatMap((field) =>
    (["asc", "desc"] as const).map((direction) => ({
      sort: [{ field, direction }],
      limit: 3,
    })),
  ),
  { sort: [], fields: ["position", "item.itemType", "item.custom"] },
];
