import { writeFile } from "node:fs/promises";
import { join } from "node:path";

// oxlint-disable-next-line no-restricted-imports
import schema from "../zotero-schema/schema.json" with { type: "json" };

interface ZoteroCslSchema {
  readonly version: number;
  readonly csl: {
    readonly types: Readonly<Record<string, readonly string[]>>;
    readonly fields: {
      readonly text: Readonly<Record<string, readonly string[]>>;
      readonly date: Readonly<Record<string, string>>;
    };
    readonly names: Readonly<Record<string, string>>;
  };
}

/**
 * Two Zotero schema field names are exposed to templates under a
 * CSL-inspired zt vocabulary name instead of their raw schema name.
 */
const ZT_FIELD_RENAMES: Readonly<Record<string, string>> = {
  abstractNote: "abstract",
  publicationTitle: "containerTitle",
};

const outputFile = join("src", "csl.ts");

await writeFile(outputFile, render(schema as ZoteroCslSchema));

/** Object-literal body, one `"key": value,` line per entry. */
function renderEntries(entries: Iterable<readonly [string, unknown]>): string {
  return Array.from(
    entries,
    ([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`,
  ).join("\n");
}

function render(schema: ZoteroCslSchema): string {
  const textFields = Object.entries(schema.csl.fields.text);
  const types = Object.entries(schema.csl.types);

  const textFieldEntries = renderEntries(
    textFields.map(([cslVar, [firstCandidate]]) => [
      cslVar,
      ZT_FIELD_RENAMES[firstCandidate!] ?? firstCandidate,
    ]),
  );

  const typeEntries = renderEntries(
    types.map(([cslType, [firstCandidate]]) => [cslType, firstCandidate]),
  );

  const textFieldCandidateEntries = renderEntries(textFields);

  const itemTypeEntries = renderEntries(
    types.flatMap(([cslType, candidates]) =>
      candidates.map((itemType) => [itemType, cslType] as const),
    ),
  );

  const dateFieldEntries = renderEntries(
    Object.entries(schema.csl.fields.date),
  );

  const creatorTypeEntries = renderEntries(Object.entries(schema.csl.names));

  return [
    "// Generated by scripts/generate-csl.ts - DO NOT EDIT.",
    `// Schema version: ${schema.version}`,
    "",
    "/**",
    " * CSL text variable -> zt vocabulary field, the first Zotero field",
    " * candidate from the Zotero schema's `csl.fields.text` section,",
    " * translated to its zt name (the CSL-inspired renames `abstractNote` ->",
    " * `abstract` and `publicationTitle` -> `containerTitle` already applied).",
    " */",
    `export const CSL_TEXT_FIELD_MAP: Readonly<Record<string, string>> = {\n${textFieldEntries}\n};`,
    "",
    "/**",
    " * CSL text variable -> every Zotero field candidate from the Zotero schema's",
    " * `csl.fields.text` section, in schema order, under their raw schema names.",
    " * Read left to right and take the first candidate the item carries a value",
    " * for, the way Zotero's `itemToCSLJSON()` does.",
    " */",
    `export const CSL_TEXT_FIELD_CANDIDATES: Readonly<\n  Record<string, readonly string[]>\n> = {\n${textFieldCandidateEntries}\n};`,
    "",
    "/**",
    " * CSL date variable -> its Zotero date field, from the Zotero schema's",
    " * `csl.fields.date` section.",
    " */",
    `export const CSL_DATE_FIELD_MAP: Readonly<Record<string, string>> = {\n${dateFieldEntries}\n};`,
    "",
    "/**",
    " * CSL type -> its first Zotero item-type candidate, from the Zotero",
    " * schema's `csl.types` section.",
    " */",
    `export const CSL_TYPE_MAP: Readonly<Record<string, string>> = {\n${typeEntries}\n};`,
    "",
    "/**",
    " * Zotero item type -> CSL type, covering every candidate in the Zotero",
    " * schema's `csl.types` section. Each Zotero item type appears under exactly",
    " * one CSL type, so this inverts `csl.types` without loss.",
    " */",
    `export const ITEM_TYPE_TO_CSL_TYPE: Readonly<Record<string, string>> = {\n${itemTypeEntries}\n};`,
    "",
    "/**",
    " * Zotero creator type -> its CSL name variable, from the Zotero schema's",
    " * `csl.names` section (its native orientation).",
    " */",
    `export const CREATOR_TYPE_TO_CSL_NAME: Readonly<Record<string, string>> = {\n${creatorTypeEntries}\n};`,
    "",
  ].join("\n");
}
