import { writeFile } from "node:fs/promises";
import { join } from "node:path";

// oxlint-disable-next-line no-restricted-imports
import schema from "../zotero-schema/schema.json" with { type: "json" };

interface ZoteroSchema {
  readonly version: number;
  readonly itemTypes: readonly ZoteroItemType[];
}

interface ZoteroItemType {
  readonly itemType: string;
  readonly fields: readonly ZoteroField[];
}

interface ZoteroField {
  readonly field: string;
  readonly baseField?: string;
}

const outputFile = join("src", "fields.ts");

await writeFile(outputFile, render(schema));

function render(schema: ZoteroSchema): string {
  const interfaces = schema.itemTypes.map(renderInterface).join("\n");
  const union = schema.itemTypes
    .map((itemType) => `  | ${interfaceName(itemType.itemType)}`)
    .join("\n");

  const aliases = collectFieldAliases(schema);
  const aliasEntries = [...aliases.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([alias, base]) => `  ${JSON.stringify(alias)}: ${JSON.stringify(base)},`,
    )
    .join("\n");

  return [
    "// Generated by scripts/generate.ts - DO NOT EDIT.",
    `// Schema version: ${schema.version}`,
    "",
    interfaces,
    `export type ItemFields =\n${union};`,
    "",
    'export const ZOTERO_DATE_FIELDS = ["date", "filingDate"] as const;',
    "",
    "/**",
    " * Maps item-type-specific field names to their canonical base field.",
    " * Built from the Zotero schema's `baseField` annotations.",
    " */",
    `export const FIELD_ALIASES: Record<string, string> = {\n${aliasEntries}\n};`,
    "",
  ].join("\n");
}

function collectFieldAliases(schema: ZoteroSchema): Map<string, string> {
  const aliases = new Map<string, string>();
  for (const itemType of schema.itemTypes) {
    for (const field of itemType.fields) {
      if (field.baseField && field.field !== field.baseField) {
        aliases.set(field.field, field.baseField);
      }
    }
  }
  return aliases;
}

function renderInterface(itemType: ZoteroItemType): string {
  const lines = [
    `export interface ${interfaceName(itemType.itemType)} {`,
    `  readonly itemType: ${JSON.stringify(itemType.itemType)};`,
  ];

  for (const field of itemType.fields) {
    lines.push(`  readonly ${field.field}?: string | null;`);
  }

  lines.push("}", "");
  return lines.join("\n");
}

function interfaceName(itemType: string): string {
  return `${itemType.charAt(0).toUpperCase()}${itemType.slice(1)}Fields`;
}
