import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

interface ZoteroSchema {
  readonly version: number;
  readonly itemTypes: readonly ZoteroItemType[];
}

interface ZoteroItemType {
  readonly itemType: string;
  readonly fields: readonly ZoteroField[];
}

interface ZoteroField {
  readonly field: string;
}

const schemaFile = join("zotero-schema", "schema.json");
const outputFile = join("src", "fields.ts");

const schema = JSON.parse(await readFile(schemaFile, "utf8")) as ZoteroSchema;

await writeFile(outputFile, render(schema));

function render(schema: ZoteroSchema): string {
  const interfaces = schema.itemTypes.map(renderInterface).join("\n");
  const union = schema.itemTypes
    .map((itemType) => `  | ${interfaceName(itemType.itemType)}`)
    .join("\n");

  return [
    "// Generated by scripts/generate.ts - DO NOT EDIT.",
    `// Schema version: ${schema.version}`,
    "",
    interfaces,
    `export type ItemFields =\n${union};`,
    "",
    'export const ZOTERO_DATE_FIELDS = ["date", "filingDate"] as const;',
    "",
  ].join("\n");
}

function renderInterface(itemType: ZoteroItemType): string {
  const lines = [
    `export interface ${interfaceName(itemType.itemType)} {`,
    `  readonly itemType: ${JSON.stringify(itemType.itemType)};`,
  ];

  for (const field of itemType.fields) {
    lines.push(`  readonly ${field.field}?: string | null;`);
  }

  lines.push("}", "");
  return lines.join("\n");
}

function interfaceName(itemType: string): string {
  return `${itemType.charAt(0).toUpperCase()}${itemType.slice(1)}Fields`;
}
