import { writeFile } from "node:fs/promises";
import { join } from "node:path";

// oxlint-disable-next-line no-restricted-imports
import schema from "../zotero-schema/schema.json" with { type: "json" };

interface ZoteroCslSchema {
  readonly version: number;
  readonly csl: {
    readonly types: Readonly<Record<string, readonly string[]>>;
    readonly fields: {
      readonly text: Readonly<Record<string, readonly string[]>>;
    };
    readonly names: Readonly<Record<string, string>>;
  };
}

/**
 * Two Zotero schema field names are exposed to templates under a
 * CSL-inspired zt vocabulary name instead of their raw schema name.
 */
const ZT_FIELD_RENAMES: Readonly<Record<string, string>> = {
  abstractNote: "abstract",
  publicationTitle: "containerTitle",
};

const outputFile = join("src", "csl.ts");

await writeFile(outputFile, render(schema as ZoteroCslSchema));

function render(schema: ZoteroCslSchema): string {
  const textFieldEntries = Object.entries(schema.csl.fields.text)
    .map(([cslVar, [firstCandidate]]) => {
      const ztField = ZT_FIELD_RENAMES[firstCandidate!] ?? firstCandidate;
      return `  ${JSON.stringify(cslVar)}: ${JSON.stringify(ztField)},`;
    })
    .join("\n");

  const typeEntries = Object.entries(schema.csl.types)
    .map(([cslType, [firstCandidate]]) => {
      return `  ${JSON.stringify(cslType)}: ${JSON.stringify(firstCandidate)},`;
    })
    .join("\n");

  const creatorTypeEntries = Object.entries(schema.csl.names)
    .map(
      ([creatorType, cslNameVar]) =>
        `  ${creatorType}: ${JSON.stringify(cslNameVar)},`,
    )
    .join("\n");

  return [
    "// Generated by scripts/generate-csl.ts - DO NOT EDIT.",
    `// Schema version: ${schema.version}`,
    "",
    "/**",
    " * CSL text variable -> zt vocabulary field, the first Zotero field",
    " * candidate from the Zotero schema's `csl.fields.text` section,",
    " * translated to its zt name (the CSL-inspired renames `abstractNote` ->",
    " * `abstract` and `publicationTitle` -> `containerTitle` already applied).",
    " */",
    `export const CSL_TEXT_FIELD_MAP: Readonly<Record<string, string>> = {\n${textFieldEntries}\n};`,
    "",
    "/**",
    " * CSL type -> its first Zotero item-type candidate, from the Zotero",
    " * schema's `csl.types` section.",
    " */",
    `export const CSL_TYPE_MAP: Readonly<Record<string, string>> = {\n${typeEntries}\n};`,
    "",
    "/**",
    " * Zotero creator type -> its CSL name variable, from the Zotero schema's",
    " * `csl.names` section (its native orientation).",
    " */",
    `export const CREATOR_TYPE_TO_CSL_NAME: Readonly<Record<string, string>> = {\n${creatorTypeEntries}\n};`,
    "",
  ].join("\n");
}
