// Generates src/field-labels.ts: Zotero's own field labels for the bundled locales.
import { writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

// oxlint-disable-next-line no-restricted-imports
import schema from "../zotero-schema/schema.json" with { type: "json" };

interface ZoteroSchema {
  readonly version: number;
  readonly locales: Readonly<Record<string, ZoteroSchemaLocale>>;
}

interface ZoteroSchemaLocale {
  readonly fields: Readonly<Record<string, string>>;
}

/** Locales whose field labels are bundled with the plugin. */
const LOCALES = ["en-US", "zh-CN"] as const;

const packageRoot = resolve(import.meta.dirname, "..");
const outputFile = join(packageRoot, "src", "field-labels.ts");

await writeFile(outputFile, render(schema));

function render(schema: ZoteroSchema): string {
  const localeUnion = LOCALES.map((locale) => JSON.stringify(locale)).join(
    " | ",
  );
  const entries = LOCALES.map((locale) => {
    const fields = schema.locales[locale]?.fields;
    if (!fields) throw new Error(`The schema has no locale ${locale}.`);
    const rows = Object.keys(fields)
      .toSorted((a, b) => a.localeCompare(b))
      .map(
        (field) =>
          `    ${JSON.stringify(field)}: ${JSON.stringify(fields[field])},`,
      )
      .join("\n");
    return `  ${JSON.stringify(locale)}: {\n${rows}\n  },`;
  }).join("\n");

  return [
    "// Generated by scripts/generate-field-labels.ts - DO NOT EDIT.",
    `// Schema version: ${schema.version}`,
    "",
    `export type FieldLabelLocale = ${localeUnion};`,
    "",
    "/**",
    " * The label Zotero shows for each item field, keyed by the canonical",
    " * field name, for every bundled locale.",
    " */",
    "export const FIELD_LABELS: Readonly<",
    "  Record<FieldLabelLocale, Readonly<Record<string, string>>>",
    `> = {\n${entries}\n};`,
    "",
  ].join("\n");
}
