import { writeFile } from "node:fs/promises";
import { join } from "node:path";

// oxlint-disable-next-line no-restricted-imports
import schema from "../zotero-schema/schema.json" with { type: "json" };

interface ZoteroSchema {
  readonly version: number;
  readonly itemTypes: readonly ZoteroSchemaItemType[];
  readonly locales: Readonly<Record<string, ZoteroSchemaLocale>>;
}

interface ZoteroSchemaItemType {
  readonly itemType: string;
}

interface ZoteroSchemaLocale {
  readonly itemTypes: Readonly<Record<string, string>>;
}

/** Locales whose item-type labels are bundled with the plugin. */
const LOCALES = ["en-US", "zh-CN"] as const;

/** Child item types excluded from the generated top-level item-type list. */
const EXCLUDED_ITEM_TYPES = new Set(["annotation", "attachment", "note"]);

const outputFile = join("src", "item-types.ts");

await writeFile(outputFile, render(schema));

function render(schema: ZoteroSchema): string {
  const itemTypes = schema.itemTypes.filter(
    (itemType) => !EXCLUDED_ITEM_TYPES.has(itemType.itemType),
  );

  const localeUnion = LOCALES.map((locale) => JSON.stringify(locale)).join(
    " | ",
  );

  const entries = itemTypes
    .map((itemType) => renderItemType(itemType, schema))
    .join("\n");

  return [
    "// Generated by scripts/generate-item-types.ts - DO NOT EDIT.",
    `// Schema version: ${schema.version}`,
    "",
    `export type ItemTypeLabelLocale = ${localeUnion};`,
    "",
    "export interface ZoteroItemType {",
    "  readonly name: string;",
    "  readonly labels: Readonly<Record<ItemTypeLabelLocale, string>>;",
    "}",
    "",
    "/**",
    " * Built-in top-level Zotero item types in schema order, excluding the",
    " * child types annotation, attachment, and note.",
    " */",
    `export const ITEM_TYPES: readonly ZoteroItemType[] = [\n${entries}\n];`,
    "",
  ].join("\n");
}

function renderItemType(
  itemType: ZoteroSchemaItemType,
  schema: ZoteroSchema,
): string {
  const labels = LOCALES.map((locale) => {
    const label = schema.locales[locale]?.itemTypes[itemType.itemType];
    return `    ${JSON.stringify(locale)}: ${JSON.stringify(label)},`;
  }).join("\n");

  return [
    "  {",
    `    name: ${JSON.stringify(itemType.itemType)},`,
    "    labels: {",
    labels,
    "    },",
    "  },",
  ].join("\n");
}
