// Generated by scripts/generate.ts - DO NOT EDIT.
// Schema version: 42

export interface AnnotationFields {
  readonly itemType: "annotation";
}

export interface ArtworkFields {
  readonly itemType: "artwork";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly artworkMedium?: string | null;
  readonly artworkSize?: string | null;
  readonly date?: string | null;
  readonly eventPlace?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface AttachmentFields {
  readonly itemType: "attachment";
  readonly title?: string | null;
  readonly accessDate?: string | null;
  readonly url?: string | null;
}

export interface AudioRecordingFields {
  readonly itemType: "audioRecording";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly audioRecordingFormat?: string | null;
  readonly seriesTitle?: string | null;
  readonly volume?: string | null;
  readonly numberOfVolumes?: string | null;
  readonly label?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly runningTime?: string | null;
  readonly ISBN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface BillFields {
  readonly itemType: "bill";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly billNumber?: string | null;
  readonly code?: string | null;
  readonly codeVolume?: string | null;
  readonly section?: string | null;
  readonly codePages?: string | null;
  readonly legislativeBody?: string | null;
  readonly session?: string | null;
  readonly history?: string | null;
  readonly date?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface BlogPostFields {
  readonly itemType: "blogPost";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly blogTitle?: string | null;
  readonly websiteType?: string | null;
  readonly date?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly ISSN?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface BookFields {
  readonly itemType: "book";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly series?: string | null;
  readonly seriesNumber?: string | null;
  readonly volume?: string | null;
  readonly numberOfVolumes?: string | null;
  readonly edition?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly originalDate?: string | null;
  readonly originalPublisher?: string | null;
  readonly originalPlace?: string | null;
  readonly format?: string | null;
  readonly numPages?: string | null;
  readonly ISBN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly ISSN?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface BookSectionFields {
  readonly itemType: "bookSection";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly bookTitle?: string | null;
  readonly series?: string | null;
  readonly seriesNumber?: string | null;
  readonly volume?: string | null;
  readonly numberOfVolumes?: string | null;
  readonly edition?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly originalDate?: string | null;
  readonly originalPublisher?: string | null;
  readonly originalPlace?: string | null;
  readonly format?: string | null;
  readonly pages?: string | null;
  readonly ISBN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly ISSN?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface CaseFields {
  readonly itemType: "case";
  readonly caseName?: string | null;
  readonly abstractNote?: string | null;
  readonly court?: string | null;
  readonly dateDecided?: string | null;
  readonly docketNumber?: string | null;
  readonly reporter?: string | null;
  readonly reporterVolume?: string | null;
  readonly firstPage?: string | null;
  readonly history?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface ComputerProgramFields {
  readonly itemType: "computerProgram";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly seriesTitle?: string | null;
  readonly versionNumber?: string | null;
  readonly date?: string | null;
  readonly system?: string | null;
  readonly company?: string | null;
  readonly place?: string | null;
  readonly programmingLanguage?: string | null;
  readonly rights?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly DOI?: string | null;
  readonly ISBN?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly shortTitle?: string | null;
  readonly extra?: string | null;
}

export interface ConferencePaperFields {
  readonly itemType: "conferencePaper";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly proceedingsTitle?: string | null;
  readonly conferenceName?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly eventPlace?: string | null;
  readonly volume?: string | null;
  readonly issue?: string | null;
  readonly numberOfVolumes?: string | null;
  readonly pages?: string | null;
  readonly series?: string | null;
  readonly seriesNumber?: string | null;
  readonly DOI?: string | null;
  readonly ISBN?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly ISSN?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface DatasetFields {
  readonly itemType: "dataset";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly identifier?: string | null;
  readonly type?: string | null;
  readonly versionNumber?: string | null;
  readonly date?: string | null;
  readonly repository?: string | null;
  readonly repositoryLocation?: string | null;
  readonly format?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface DictionaryEntryFields {
  readonly itemType: "dictionaryEntry";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly dictionaryTitle?: string | null;
  readonly series?: string | null;
  readonly seriesNumber?: string | null;
  readonly volume?: string | null;
  readonly numberOfVolumes?: string | null;
  readonly edition?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly pages?: string | null;
  readonly ISBN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface DocumentFields {
  readonly itemType: "document";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly type?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface EmailFields {
  readonly itemType: "email";
  readonly subject?: string | null;
  readonly abstractNote?: string | null;
  readonly date?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface EncyclopediaArticleFields {
  readonly itemType: "encyclopediaArticle";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly encyclopediaTitle?: string | null;
  readonly series?: string | null;
  readonly seriesNumber?: string | null;
  readonly volume?: string | null;
  readonly numberOfVolumes?: string | null;
  readonly edition?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly pages?: string | null;
  readonly ISBN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface FilmFields {
  readonly itemType: "film";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly distributor?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly genre?: string | null;
  readonly videoRecordingFormat?: string | null;
  readonly runningTime?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface ForumPostFields {
  readonly itemType: "forumPost";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly forumTitle?: string | null;
  readonly postType?: string | null;
  readonly date?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface HearingFields {
  readonly itemType: "hearing";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly committee?: string | null;
  readonly publisher?: string | null;
  readonly numberOfVolumes?: string | null;
  readonly documentNumber?: string | null;
  readonly pages?: string | null;
  readonly legislativeBody?: string | null;
  readonly session?: string | null;
  readonly history?: string | null;
  readonly date?: string | null;
  readonly place?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface InstantMessageFields {
  readonly itemType: "instantMessage";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly date?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface InterviewFields {
  readonly itemType: "interview";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly interviewMedium?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface JournalArticleFields {
  readonly itemType: "journalArticle";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly publicationTitle?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly volume?: string | null;
  readonly issue?: string | null;
  readonly section?: string | null;
  readonly partNumber?: string | null;
  readonly partTitle?: string | null;
  readonly pages?: string | null;
  readonly series?: string | null;
  readonly seriesTitle?: string | null;
  readonly seriesText?: string | null;
  readonly journalAbbreviation?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly PMID?: string | null;
  readonly PMCID?: string | null;
  readonly ISSN?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface LetterFields {
  readonly itemType: "letter";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly letterType?: string | null;
  readonly date?: string | null;
  readonly eventPlace?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface MagazineArticleFields {
  readonly itemType: "magazineArticle";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly publicationTitle?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly volume?: string | null;
  readonly issue?: string | null;
  readonly pages?: string | null;
  readonly ISSN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface ManuscriptFields {
  readonly itemType: "manuscript";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly manuscriptType?: string | null;
  readonly institution?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly numPages?: string | null;
  readonly number?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface MapFields {
  readonly itemType: "map";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly mapType?: string | null;
  readonly scale?: string | null;
  readonly seriesTitle?: string | null;
  readonly edition?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly DOI?: string | null;
  readonly ISBN?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface NewspaperArticleFields {
  readonly itemType: "newspaperArticle";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly publicationTitle?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly volume?: string | null;
  readonly issue?: string | null;
  readonly edition?: string | null;
  readonly section?: string | null;
  readonly pages?: string | null;
  readonly ISSN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface NoteFields {
  readonly itemType: "note";
}

export interface PatentFields {
  readonly itemType: "patent";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly place?: string | null;
  readonly country?: string | null;
  readonly assignee?: string | null;
  readonly issuingAuthority?: string | null;
  readonly patentNumber?: string | null;
  readonly filingDate?: string | null;
  readonly pages?: string | null;
  readonly applicationNumber?: string | null;
  readonly priorityNumbers?: string | null;
  readonly issueDate?: string | null;
  readonly priorityDate?: string | null;
  readonly references?: string | null;
  readonly legalStatus?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface PodcastFields {
  readonly itemType: "podcast";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly seriesTitle?: string | null;
  readonly episodeNumber?: string | null;
  readonly audioFileType?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly runningTime?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface PreprintFields {
  readonly itemType: "preprint";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly genre?: string | null;
  readonly repository?: string | null;
  readonly archiveID?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly series?: string | null;
  readonly seriesNumber?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface PresentationFields {
  readonly itemType: "presentation";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly presentationType?: string | null;
  readonly date?: string | null;
  readonly meetingName?: string | null;
  readonly place?: string | null;
  readonly series?: string | null;
  readonly sessionTitle?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface RadioBroadcastFields {
  readonly itemType: "radioBroadcast";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly programTitle?: string | null;
  readonly episodeNumber?: string | null;
  readonly audioRecordingFormat?: string | null;
  readonly network?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly runningTime?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface ReportFields {
  readonly itemType: "report";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly reportNumber?: string | null;
  readonly reportType?: string | null;
  readonly institution?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly seriesTitle?: string | null;
  readonly seriesNumber?: string | null;
  readonly pages?: string | null;
  readonly DOI?: string | null;
  readonly ISBN?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly ISSN?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface StandardFields {
  readonly itemType: "standard";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly organization?: string | null;
  readonly committee?: string | null;
  readonly type?: string | null;
  readonly number?: string | null;
  readonly versionNumber?: string | null;
  readonly edition?: string | null;
  readonly status?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly partNumber?: string | null;
  readonly partTitle?: string | null;
  readonly ISBN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly numPages?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface StatuteFields {
  readonly itemType: "statute";
  readonly nameOfAct?: string | null;
  readonly abstractNote?: string | null;
  readonly code?: string | null;
  readonly codeNumber?: string | null;
  readonly publicLawNumber?: string | null;
  readonly dateEnacted?: string | null;
  readonly pages?: string | null;
  readonly section?: string | null;
  readonly session?: string | null;
  readonly history?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface ThesisFields {
  readonly itemType: "thesis";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly thesisType?: string | null;
  readonly university?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly series?: string | null;
  readonly seriesNumber?: string | null;
  readonly numPages?: string | null;
  readonly DOI?: string | null;
  readonly ISBN?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly ISSN?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface TvBroadcastFields {
  readonly itemType: "tvBroadcast";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly programTitle?: string | null;
  readonly episodeNumber?: string | null;
  readonly videoRecordingFormat?: string | null;
  readonly network?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly runningTime?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface VideoRecordingFields {
  readonly itemType: "videoRecording";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly videoRecordingFormat?: string | null;
  readonly seriesTitle?: string | null;
  readonly volume?: string | null;
  readonly numberOfVolumes?: string | null;
  readonly studio?: string | null;
  readonly place?: string | null;
  readonly date?: string | null;
  readonly runningTime?: string | null;
  readonly ISBN?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly archive?: string | null;
  readonly archiveLocation?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly libraryCatalog?: string | null;
  readonly callNumber?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export interface WebpageFields {
  readonly itemType: "webpage";
  readonly title?: string | null;
  readonly abstractNote?: string | null;
  readonly websiteTitle?: string | null;
  readonly websiteType?: string | null;
  readonly date?: string | null;
  readonly publisher?: string | null;
  readonly place?: string | null;
  readonly DOI?: string | null;
  readonly citationKey?: string | null;
  readonly url?: string | null;
  readonly accessDate?: string | null;
  readonly shortTitle?: string | null;
  readonly language?: string | null;
  readonly rights?: string | null;
  readonly extra?: string | null;
}

export type ItemFields =
  | AnnotationFields
  | ArtworkFields
  | AttachmentFields
  | AudioRecordingFields
  | BillFields
  | BlogPostFields
  | BookFields
  | BookSectionFields
  | CaseFields
  | ComputerProgramFields
  | ConferencePaperFields
  | DatasetFields
  | DictionaryEntryFields
  | DocumentFields
  | EmailFields
  | EncyclopediaArticleFields
  | FilmFields
  | ForumPostFields
  | HearingFields
  | InstantMessageFields
  | InterviewFields
  | JournalArticleFields
  | LetterFields
  | MagazineArticleFields
  | ManuscriptFields
  | MapFields
  | NewspaperArticleFields
  | NoteFields
  | PatentFields
  | PodcastFields
  | PreprintFields
  | PresentationFields
  | RadioBroadcastFields
  | ReportFields
  | StandardFields
  | StatuteFields
  | ThesisFields
  | TvBroadcastFields
  | VideoRecordingFields
  | WebpageFields;

export const ZOTERO_DATE_FIELDS = ["date", "filingDate"] as const;

/**
 * Maps item-type-specific field names to their canonical base field.
 * Built from the Zotero schema's `baseField` annotations.
 */
export const FIELD_ALIASES: Record<string, string> = {
  archiveID: "number",
  artworkMedium: "medium",
  audioFileType: "medium",
  audioRecordingFormat: "medium",
  billNumber: "number",
  blogTitle: "publicationTitle",
  bookTitle: "publicationTitle",
  caseName: "title",
  codePages: "pages",
  codeVolume: "volume",
  company: "publisher",
  court: "authority",
  dateDecided: "date",
  dateEnacted: "date",
  dictionaryTitle: "publicationTitle",
  distributor: "publisher",
  docketNumber: "number",
  documentNumber: "number",
  encyclopediaTitle: "publicationTitle",
  episodeNumber: "number",
  firstPage: "pages",
  format: "medium",
  forumTitle: "publicationTitle",
  genre: "type",
  identifier: "number",
  institution: "publisher",
  interviewMedium: "medium",
  issueDate: "date",
  issuingAuthority: "authority",
  label: "publisher",
  legalStatus: "status",
  legislativeBody: "authority",
  letterType: "type",
  manuscriptType: "type",
  mapType: "type",
  nameOfAct: "title",
  network: "publisher",
  organization: "authority",
  patentNumber: "number",
  postType: "type",
  presentationType: "type",
  priorityDate: "originalDate",
  proceedingsTitle: "publicationTitle",
  programTitle: "publicationTitle",
  publicLawNumber: "number",
  reporterVolume: "volume",
  reportNumber: "number",
  reportType: "type",
  repository: "publisher",
  repositoryLocation: "place",
  sessionTitle: "publicationTitle",
  studio: "publisher",
  subject: "title",
  thesisType: "type",
  university: "publisher",
  videoRecordingFormat: "medium",
  websiteTitle: "publicationTitle",
  websiteType: "type",
};
