// Generated by scripts/generate-item-types.ts - DO NOT EDIT.
// Schema version: 42

export type ItemTypeLabelLocale = "en-US" | "zh-CN";

export interface ZoteroItemType {
  readonly name: string;
  readonly labels: Readonly<Record<ItemTypeLabelLocale, string>>;
}

/**
 * Built-in top-level Zotero item types in schema order, excluding the
 * child types annotation, attachment, and note.
 */
export const ITEM_TYPES: readonly ZoteroItemType[] = [
  {
    name: "artwork",
    labels: {
      "en-US": "Artwork",
      "zh-CN": "艺术品",
    },
  },
  {
    name: "audioRecording",
    labels: {
      "en-US": "Audio Recording",
      "zh-CN": "音频",
    },
  },
  {
    name: "bill",
    labels: {
      "en-US": "Bill",
      "zh-CN": "法案",
    },
  },
  {
    name: "blogPost",
    labels: {
      "en-US": "Blog Post",
      "zh-CN": "博客帖文",
    },
  },
  {
    name: "book",
    labels: {
      "en-US": "Book",
      "zh-CN": "图书",
    },
  },
  {
    name: "bookSection",
    labels: {
      "en-US": "Book Section",
      "zh-CN": "图书章节",
    },
  },
  {
    name: "case",
    labels: {
      "en-US": "Case",
      "zh-CN": "司法案例",
    },
  },
  {
    name: "computerProgram",
    labels: {
      "en-US": "Software",
      "zh-CN": "软件",
    },
  },
  {
    name: "conferencePaper",
    labels: {
      "en-US": "Conference Paper",
      "zh-CN": "会议论文",
    },
  },
  {
    name: "dataset",
    labels: {
      "en-US": "Dataset",
      "zh-CN": "数据集",
    },
  },
  {
    name: "dictionaryEntry",
    labels: {
      "en-US": "Dictionary Entry",
      "zh-CN": "词条",
    },
  },
  {
    name: "document",
    labels: {
      "en-US": "Document",
      "zh-CN": "文档",
    },
  },
  {
    name: "email",
    labels: {
      "en-US": "E-mail",
      "zh-CN": "电子邮件",
    },
  },
  {
    name: "encyclopediaArticle",
    labels: {
      "en-US": "Encyclopedia Article",
      "zh-CN": "百科条目",
    },
  },
  {
    name: "film",
    labels: {
      "en-US": "Film",
      "zh-CN": "电影",
    },
  },
  {
    name: "forumPost",
    labels: {
      "en-US": "Forum Post",
      "zh-CN": "论坛帖文",
    },
  },
  {
    name: "hearing",
    labels: {
      "en-US": "Hearing",
      "zh-CN": "听证会",
    },
  },
  {
    name: "instantMessage",
    labels: {
      "en-US": "Instant Message",
      "zh-CN": "即时消息",
    },
  },
  {
    name: "interview",
    labels: {
      "en-US": "Interview",
      "zh-CN": "访谈",
    },
  },
  {
    name: "journalArticle",
    labels: {
      "en-US": "Journal Article",
      "zh-CN": "期刊文章",
    },
  },
  {
    name: "letter",
    labels: {
      "en-US": "Letter",
      "zh-CN": "信件",
    },
  },
  {
    name: "magazineArticle",
    labels: {
      "en-US": "Magazine Article",
      "zh-CN": "杂志文章",
    },
  },
  {
    name: "manuscript",
    labels: {
      "en-US": "Manuscript",
      "zh-CN": "手稿",
    },
  },
  {
    name: "map",
    labels: {
      "en-US": "Map",
      "zh-CN": "地图",
    },
  },
  {
    name: "newspaperArticle",
    labels: {
      "en-US": "Newspaper Article",
      "zh-CN": "报纸文章",
    },
  },
  {
    name: "patent",
    labels: {
      "en-US": "Patent",
      "zh-CN": "专利",
    },
  },
  {
    name: "podcast",
    labels: {
      "en-US": "Podcast",
      "zh-CN": "播客",
    },
  },
  {
    name: "preprint",
    labels: {
      "en-US": "Preprint",
      "zh-CN": "预印本",
    },
  },
  {
    name: "presentation",
    labels: {
      "en-US": "Presentation",
      "zh-CN": "演示文档",
    },
  },
  {
    name: "radioBroadcast",
    labels: {
      "en-US": "Radio Broadcast",
      "zh-CN": "电台广播",
    },
  },
  {
    name: "report",
    labels: {
      "en-US": "Report",
      "zh-CN": "报告",
    },
  },
  {
    name: "standard",
    labels: {
      "en-US": "Standard",
      "zh-CN": "标准",
    },
  },
  {
    name: "statute",
    labels: {
      "en-US": "Statute",
      "zh-CN": "法律",
    },
  },
  {
    name: "thesis",
    labels: {
      "en-US": "Thesis",
      "zh-CN": "学位论文",
    },
  },
  {
    name: "tvBroadcast",
    labels: {
      "en-US": "TV Broadcast",
      "zh-CN": "电视广播",
    },
  },
  {
    name: "videoRecording",
    labels: {
      "en-US": "Video Recording",
      "zh-CN": "视频",
    },
  },
  {
    name: "webpage",
    labels: {
      "en-US": "Web Page",
      "zh-CN": "网页",
    },
  },
];
