// Generates the committed contract IR and the per-root JSON Schemas from the `zt` template types.
//
// The effective parser is ts-morph's vendored frozen TypeScript 6, not the
// repo's TypeScript 7 — TS 7 ships no programmatic API until 7.1, so adding a
// `typescript` dependency here would be a no-op. A syntax gap surfaces as a
// parse error in the CI regeneration check, never as silently wrong output.
//
// @see docs/adr/0015-template-contract-artifacts-generate-from-ts-types.md
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { Project, ts } from "ts-morph";

import { FIELD_ALIASES } from "@zotlit/zotero-types";

// oxlint-disable-next-line no-restricted-imports
import zoteroSchema from "../../zotero-types/zotero-schema/schema.json" with { type: "json" };
import {
  CONTRACT_VERSION,
  templateSlotsForRoot,
  type ContractRoot,
} from "../src/contract/roots.ts";
import { ZT_FIELD_ALIASES } from "../src/lib/context/zt-field-aliases.ts";
import { CHILD_ITEM_TYPES } from "../src/lib/item-types.ts";
import { ContractExtractor } from "./contract/extract.ts";
import {
  type ContractIR,
  type ContractReference,
  type ContractRootIR,
} from "./contract/ir.ts";
import { toJsonSchema } from "./contract/json-schema.ts";

const BANNER = "Generated by scripts/generate-contract.ts - DO NOT EDIT.";
const OUT_DIR = join("src", "contract", "generated");

/** Where each root's `zt` type is declared. Adding a {@link ContractRoot} is a type error until listed. */
const ROOT_DECLARATIONS = {
  note: {
    module: "src/lib/context/zt-template-note.ts",
    type: "NoteTemplateContext",
    references: [
      { owner: "TemplateAnnotation", member: "parentItem", path: "zt" },
    ],
  },
  annotation: {
    module: "src/lib/context/zt-template-annot.ts",
    type: "AnnotationTemplateContext",
    references: [],
  },
  filename: {
    module: "src/lib/context/zt-template-item.ts",
    type: "TemplateFilenameItemData",
    references: [],
  },
} as const satisfies Record<
  ContractRoot,
  {
    module: string;
    type: string;
    references: readonly ContractReference[];
  }
>;

const EMITTED_ROOTS = Object.keys(ROOT_DECLARATIONS) as ContractRoot[];

interface ZoteroSchema {
  readonly itemTypes: readonly {
    readonly itemType: string;
    readonly fields: readonly { readonly field: string }[];
  }[];
}

const CHILD_ITEM_TYPE_NAMES: ReadonlySet<string> = new Set(CHILD_ITEM_TYPES);

const project = new Project({ tsConfigFilePath: "tsconfig.lib.json" });
const extractor = new ContractExtractor(resolve("src"));

const roots: Partial<Record<ContractRoot, ContractRootIR>> = {};
for (const root of EMITTED_ROOTS) {
  const { module, type, references } = ROOT_DECLARATIONS[root];
  const declaration = project
    .getSourceFileOrThrow(module)
    .getInterfaceOrThrow(type);
  roots[root] = {
    type: extractor.addRoot(declaration),
    templates: templateSlotsForRoot(root),
    references,
  };
}

const ir: ContractIR = {
  $comment: BANNER,
  contractVersion: CONTRACT_VERSION,
  roots,
  itemTypes: extractItemTypes(zoteroSchema),
  types: extractor.types,
};

// Emptied first, so dropping a root deletes its committed schema instead of
// leaving one the regeneration check would never notice.
await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });
await writeJson("ir.json", ir);
for (const root of EMITTED_ROOTS) {
  await writeJson(`${root}.schema.json`, toJsonSchema(ir, root));
}

console.log(
  `Contract v${CONTRACT_VERSION}: ${EMITTED_ROOTS.join(", ")} from ${
    Object.keys(ir.types).length
  } types (TypeScript ${ts.version}).`,
);

function writeJson(name: string, value: unknown): Promise<void> {
  return writeFile(join(OUT_DIR, name), `${JSON.stringify(value, null, 2)}\n`);
}

function extractItemTypes(
  schema: ZoteroSchema,
): Record<string, readonly string[]> {
  return Object.fromEntries(
    schema.itemTypes
      .filter(({ itemType }) => !CHILD_ITEM_TYPE_NAMES.has(itemType))
      .map(({ itemType, fields }) => {
        const names = new Set<string>();
        for (const { field } of fields) {
          const canonical = FIELD_ALIASES[field] ?? field;
          names.add(canonical);
          for (const [alias, source] of Object.entries(ZT_FIELD_ALIASES)) {
            if (source === canonical) names.add(alias);
          }
        }
        return [itemType, [...names].sort()] as const;
      }),
  );
}
