// Generates the committed contract IR and the per-root JSON Schemas from the `zt` template types.
//
// The effective parser is ts-morph's vendored frozen TypeScript 6, not the
// repo's TypeScript 7 — TS 7 ships no programmatic API until 7.1, so adding a
// `typescript` dependency here would be a no-op. A syntax gap surfaces as a
// parse error in the CI regeneration check, never as silently wrong output.
//
// @see docs/adr/0015-template-contract-artifacts-generate-from-ts-types.md
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { Project, ts } from "ts-morph";

import {
  CONTRACT_VERSION,
  templateSlotsForRoot,
  type ContractRoot,
} from "../src/contract/roots.ts";
import { ContractExtractor } from "./contract/extract.ts";
import { type ContractIR, type ContractRootIR } from "./contract/ir.ts";
import { toJsonSchema } from "./contract/json-schema.ts";

const BANNER = "Generated by scripts/generate-contract.ts - DO NOT EDIT.";
const OUT_DIR = join("src", "contract", "generated");

/** Where each root's `zt` type is declared. Adding a {@link ContractRoot} is a type error until listed. */
const ROOT_DECLARATIONS = {
  note: {
    module: "src/lib/context/zt-template-note.ts",
    type: "NoteTemplateContext",
  },
  annotation: {
    module: "src/lib/context/zt-template-annot.ts",
    type: "AnnotationTemplateContext",
  },
  filename: {
    module: "src/lib/context/zt-template-item.ts",
    type: "TemplateFilenameItemData",
  },
} as const satisfies Record<ContractRoot, { module: string; type: string }>;

/** Roots emitted so far. The note and annotation roots follow. */
const EMITTED_ROOTS = ["filename"] as const satisfies readonly ContractRoot[];

const project = new Project({ tsConfigFilePath: "tsconfig.lib.json" });
const extractor = new ContractExtractor(resolve("src"));

const roots: Partial<Record<ContractRoot, ContractRootIR>> = {};
for (const root of EMITTED_ROOTS) {
  const { module, type } = ROOT_DECLARATIONS[root];
  const declaration = project
    .getSourceFileOrThrow(module)
    .getInterfaceOrThrow(type);
  roots[root] = {
    type: extractor.addRoot(declaration),
    templates: templateSlotsForRoot(root),
  };
}

const ir: ContractIR = {
  $comment: BANNER,
  contractVersion: CONTRACT_VERSION,
  roots,
  types: extractor.types,
};

// Emptied first, so dropping a root deletes its committed schema instead of
// leaving one the regeneration check would never notice.
await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });
await writeJson("ir.json", ir);
for (const root of EMITTED_ROOTS) {
  await writeJson(`${root}.schema.json`, toJsonSchema(ir, root));
}

console.log(
  `Contract v${CONTRACT_VERSION}: ${EMITTED_ROOTS.join(", ")} from ${
    Object.keys(ir.types).length
  } types (TypeScript ${ts.version}).`,
);

function writeJson(name: string, value: unknown): Promise<void> {
  return writeFile(join(OUT_DIR, name), `${JSON.stringify(value, null, 2)}\n`);
}
