// Compiler-seam tests for generated message wrappers and Language Packs.

import { loadProjectFromDirectory } from "@inlang/sdk";
import { execFile } from "node:child_process";
import fs from "node:fs";
import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { createServer } from "vite";
import { describe, expect, test } from "vitest";

import {
  formatCompilerWarnings,
  compile,
  compileProject,
  type CompileResult,
} from "./compiler.js";
import {
  LanguagePackSchemaVersionError,
  validateLanguagePack,
  type LanguagePackRuntime,
  type TargetLocaleMessages,
} from "./index.js";
import {
  addLocale,
  addSourcePattern,
  createFixtureProject,
  createTemporaryDirectory,
  writeCatalog,
} from "./test-fixtures.js";

const repoRoot = resolve(import.meta.dirname, "..", "..", "..");
const realProjectPath = join(repoRoot, "project.inlang");
const execFileAsync = promisify(execFile);
const TARGET_LOCALE_PREFIXES = ["notice_pack_"];

describe("generateLanguagePacks", () => {
  test("emits a stable partial-safe pack for each configured remote locale", async () => {
    const projectPath = await createFixtureProject({
      hello: "world",
      creator_summary: [
        {
          declarations: ["input count", "input first", "input second"],
          selectors: ["count"],
          match: {
            "count=1": "{first}",
            "count=2": "⁨{first}⁩ and ⁨{second}⁩",
            "count=*": "{first} et al.",
          },
        },
      ],
    });
    await addLocale(projectPath, "zh-CN", {
      hello: "世界",
      creator_summary: [
        {
          declarations: ["input count", "input first", "input second"],
          selectors: ["count"],
          match: {
            "count=1": "{first}",
            "count=2": "⁨{first}⁩ 和 ⁨{second}⁩",
            "count=*": "{first} 等",
          },
        },
      ],
    });
    const firstOutputDirectory = await createTemporaryDirectory();
    const secondOutputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({
      projectPath,
      outputDirectory: firstOutputDirectory,
    });
    const chinesePackPath = join(firstOutputDirectory, "zh-CN.json");
    const englishPackPath = join(firstOutputDirectory, "en.json");
    const beforeMtime = (await stat(chinesePackPath)).mtimeMs;

    await generateLanguagePacks({
      projectPath,
      outputDirectory: firstOutputDirectory,
    });
    await generateLanguagePacks({
      projectPath,
      outputDirectory: secondOutputDirectory,
    });

    const chinesePackText = await readFile(chinesePackPath, "utf8");
    const chinesePack = JSON.parse(chinesePackText);
    await expect(readFile(englishPackPath, "utf8")).resolves.toBeTruthy();
    expect(chinesePack).toMatchObject({
      schemaVersion: 1,
      locale: "zh-CN",
      messages: {
        hello: "世界",
        creator_summary: {
          declarations: [
            { type: "input", name: "count" },
            { type: "input", name: "first" },
            { type: "input", name: "second" },
          ],
        },
      },
    });
    expect(
      validateLanguagePack(chinesePackText, { expectedLocale: "zh-CN" }),
    ).toEqual(chinesePack);
    // Repeating the same generation is a byte-identical write-skip.
    expect((await stat(chinesePackPath)).mtimeMs).toBe(beforeMtime);
    expect(chinesePackText).toBe(
      await readFile(join(secondOutputDirectory, "zh-CN.json"), "utf8"),
    );
  });

  test("emits a byte-deterministic catalog listing only remote locales", async () => {
    const projectPath = await createFixtureProject({ hello: "world" });
    await addLocale(projectPath, "zh-CN", { hello: "世界" });
    await addLocale(projectPath, "fr", { hello: "monde" });
    const outputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({ projectPath, outputDirectory });

    const catalog = await readFile(join(outputDirectory, "catalog.ts"), "utf8");
    expect(catalog).toBe(
      [
        "// Generated by @zotlit/obsidian-i18n. Do not edit.",
        "",
        "export const catalog = {",
        '  baseLocale: "en",',
        "  packs: {",
        '    "fr": { fileName: "fr.json" },',
        '    "zh-CN": { fileName: "zh-CN.json" },',
        "  },",
        "} as const;",
        "",
      ].join("\n"),
    );
  });

  test("removing a locale updates the catalog and removes the stale pack", async () => {
    const projectPath = await createFixtureProject({ greeting: "Hello" });
    await addLocale(projectPath, "zh-CN", { greeting: "你好" });
    const outputDirectory = await createTemporaryDirectory();
    await generateLanguagePacks({ projectPath, outputDirectory });
    expect(
      await readFile(join(outputDirectory, "catalog.ts"), "utf8"),
    ).toContain('"zh-CN"');

    const settingsPath = join(projectPath, "settings.json");
    const settings = JSON.parse(await readFile(settingsPath, "utf8"));
    settings.locales = ["en"];
    await writeFile(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
    await generateLanguagePacks({ projectPath, outputDirectory });

    expect(
      await readFile(join(outputDirectory, "catalog.ts"), "utf8"),
    ).not.toContain("zh-CN");
    await expect(
      readFile(join(outputDirectory, "zh-CN.json")),
    ).rejects.toMatchObject({ code: "ENOENT" });
  });

  test("emits typed wrappers and a normalized base pack", async () => {
    const projectPath = await createFixtureProject({
      hello: "world",
      creator_summary: [
        {
          declarations: ["input count", "input first", "input second"],
          selectors: ["count"],
          match: {
            "count=1": "{first}",
            "count=2": "⁨{first}⁩ and ⁨{second}⁩",
            "count=*": "{first} et al.",
          },
        },
      ],
    });
    const outputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({
      projectPath,
      outputDirectory,
    });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    const runtime = await readFile(join(outputDirectory, "runtime.ts"), "utf8");
    const packText = await readFile(join(outputDirectory, "en.json"), "utf8");
    const pack = JSON.parse(packText);

    expect(facade).toContain("export const hello = (): string");
    expect(facade).toContain('import { translate } from "./runtime.js";');
    expect(facade).toContain(
      "export const creator_summary = (inputs: { count: number; first: string | number; second: string | number }): string",
    );
    expect(facade).not.toContain("Temporal");
    expect(runtime).toContain("createLanguagePackRuntime(basePack)");
    expect(runtime).toContain("runtime.translate.bind(runtime)");
    expect(pack).toMatchObject({
      schemaVersion: 1,
      locale: "en",
      messages: {
        hello: "world",
        creator_summary: {
          declarations: [
            { type: "input", name: "count" },
            { type: "input", name: "first" },
            { type: "input", name: "second" },
          ],
          variants: [
            {
              matches: [{ type: "literal", key: "count", value: "1" }],
              pattern: [{ type: "variable", name: "first" }],
            },
            {
              matches: [{ type: "literal", key: "count", value: "2" }],
              pattern: [
                { type: "text", value: "⁨" },
                { type: "variable", name: "first" },
                { type: "text", value: "⁩ and ⁨" },
                { type: "variable", name: "second" },
                { type: "text", value: "⁩" },
              ],
            },
            {
              matches: [{ type: "catchall", key: "count" }],
              pattern: [
                { type: "variable", name: "first" },
                { type: "text", value: " et al." },
              ],
            },
          ],
        },
      },
    });
    expect(packText).not.toMatch(
      /\b[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/i,
    );
    await typecheckGeneratedOutput(outputDirectory);
  });

  test("excludes docs-only messages from every artifact", async () => {
    const projectPath = await createFixtureProject({
      docs_example: "Docs {#link}only{/link}",
      plugin_example: "Plugin text",
    });
    const outputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({ projectPath, outputDirectory });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    const pack = await readFile(join(outputDirectory, "en.json"), "utf8");
    expect(facade).toContain("plugin_example");
    expect(pack).toContain("plugin_example");
    expect(facade).not.toContain("docs_example");
    expect(pack).not.toContain("docs_example");
  });

  test("bundles a per-locale subset for the configured prefixes", async () => {
    const projectPath = await createFixtureProject({
      notice_pack_offer: "A pack for {language} is available.",
      docs_notice_pack_offer: "Docs only",
      plugin_example: "Plugin text",
    });
    await addLocale(projectPath, "zh-CN", {
      notice_pack_offer: "{language} 语言包可用。",
      docs_notice_pack_offer: "仅文档",
      plugin_example: "插件文本",
    });
    const outputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({
      projectPath,
      outputDirectory,
      targetLocaleMessagePrefixes: TARGET_LOCALE_PREFIXES,
    });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    const runtime = await readFile(join(outputDirectory, "runtime.ts"), "utf8");
    await using generated = await loadGeneratedModules(outputDirectory);
    expect(generated.targetLocaleMessages).toEqual({
      // The base locale ships as the bundled base pack the ladder already
      // falls back to, so it carries no subset of its own.
      "zh-CN": {
        notice_pack_offer: {
          declarations: [{ type: "input", name: "language" }],
          variants: [
            {
              matches: [],
              pattern: [
                { type: "variable", name: "language" },
                { type: "text", value: " 语言包可用。" },
              ],
            },
          ],
        },
      },
    });
    expect(facade).toContain(
      'export const notice_pack_offer = (inputs: { language: string | number }): string => translateTarget("notice_pack_offer", inputs);',
    );
    expect(facade).toContain(
      'export const plugin_example = (): string => translate("plugin_example");',
    );
    expect(facade).toContain(
      'import { translate, translateTarget } from "./runtime.js";',
    );
    expect(runtime).toContain(
      "createLanguagePackRuntime(basePack, { targetLocaleMessages })",
    );
    expect(runtime).toContain(
      "export const translateTarget = runtime.translateTarget.bind(runtime);",
    );
    await typecheckGeneratedOutput(outputDirectory, {
      include: ["target-locale-messages.ts"],
    });
  });

  test("renders target-locale text through the generated wrappers", async () => {
    const projectPath = await createFixtureProject({
      notice_pack_offer: "A pack for {language} is available.",
      notice_pack_untranslated: "Restart to apply.",
      plugin_example: "Plugin text",
    });
    await addLocale(projectPath, "zh-CN", {
      notice_pack_offer: "{language} 语言包可用。",
      plugin_example: "插件文本",
    });
    const outputDirectory = await createTemporaryDirectory();
    await generateLanguagePacks({
      projectPath,
      outputDirectory,
      targetLocaleMessagePrefixes: TARGET_LOCALE_PREFIXES,
    });

    await using generated = await loadGeneratedModules<{
      notice_pack_offer(inputs: { language: string }): string;
      notice_pack_untranslated(): string;
      plugin_example(): string;
    }>(outputDirectory);
    generated.runtime.setTargetLocale("zh-CN");
    // An installed pack must not reach a Target-Locale Message, and must still
    // serve everything else.
    generated.runtime.install({
      schemaVersion: 1,
      locale: "zh-CN",
      messages: {
        notice_pack_offer: "来自语言包",
        plugin_example: "来自语言包",
      },
    });

    expect(generated.messages.notice_pack_offer({ language: "简体中文" })).toBe(
      "简体中文 语言包可用。",
    );
    // Untranslated in the subset: this one message degrades to the base locale.
    expect(generated.messages.notice_pack_untranslated()).toBe(
      "Restart to apply.",
    );
    expect(generated.messages.plugin_example()).toBe("来自语言包");
  });

  test("emits no target-locale artifact without configured prefixes", async () => {
    const projectPath = await createFixtureProject({
      notice_pack_offer: "A pack is available.",
    });
    const outputDirectory = await createTemporaryDirectory();

    await compile({
      root: dirname(projectPath),
      project: "project.inlang",
      output: outputDirectory,
    });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    const runtime = await readFile(join(outputDirectory, "runtime.ts"), "utf8");
    expect(await readdir(outputDirectory)).not.toContain(
      "target-locale-messages.ts",
    );
    expect(facade).toContain('import { translate } from "./runtime.js";');
    expect(facade).not.toContain("translateTarget");
    expect(runtime).toContain("createLanguagePackRuntime(basePack)");
    expect(runtime).not.toContain("translateTarget");
  });

  test("removes the stale target-locale artifact after the prefixes are dropped", async () => {
    const projectPath = await createFixtureProject({
      notice_pack_offer: "A pack is available.",
    });
    const outputDirectory = await createTemporaryDirectory();
    await generateLanguagePacks({
      projectPath,
      outputDirectory,
      targetLocaleMessagePrefixes: TARGET_LOCALE_PREFIXES,
    });
    expect(await readdir(outputDirectory)).toContain(
      "target-locale-messages.ts",
    );

    await compile({
      root: dirname(projectPath),
      project: "project.inlang",
      output: outputDirectory,
    });

    expect(await readdir(outputDirectory)).not.toContain(
      "target-locale-messages.ts",
    );
  });

  test("includes every Message by default and resolves paths from the explicit root", async () => {
    const projectPath = await createFixtureProject({
      docs_example: "Docs only",
      plugin_example: "Plugin text",
    });
    const outputDirectory = await createTemporaryDirectory();

    await compile({
      root: dirname(projectPath),
      project: "project.inlang",
      output: outputDirectory,
    });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    expect(facade).toContain("docs_example");
    expect(facade).toContain("plugin_example");
  });

  test("applies raw-source validation through the in-memory compiler seam", async () => {
    const projectPath = await createFixtureProject({
      greeting: "Hello",
    });
    const project = await loadProjectFromDirectory({
      path: projectPath,
      fs,
    });
    try {
      await expect(
        compileProject({
          project,
          sourceCatalogs: [
            {
              locale: "en",
              path: "/catalogs/base/en.json",
              contents: '{\n  "greeting": "Bad {#link}markup{/link}"\n}\n',
              mergePrecedence: 0,
            },
          ],
        }),
      ).rejects.toThrow(/\/catalogs\/base\/en\.json:2:3.*markup-start/);
    } finally {
      await project.close();
    }
  });

  test("honors multiple source patterns and reports every contributing path", async () => {
    const projectPath = await createFixtureProject({
      greeting: "Hello",
      base_only: "Base",
    });
    const overridePath = await addSourcePattern(projectPath, "overrides", {
      messages: { greeting: "Hello from override" },
    });
    const outputDirectory = await createTemporaryDirectory();

    const result = await generateLanguagePacks({
      projectPath,
      outputDirectory,
    });

    const pack = JSON.parse(
      await readFile(join(outputDirectory, "en.json"), "utf8"),
    );
    expect(pack.messages.greeting).toBe("Hello from override");
    expect(result.sourcePaths).toEqual([
      join(dirname(projectPath), "messages", "en.json"),
      overridePath,
    ]);
  });

  test("attributes a message diagnostic to the catalog that wins the merge", async () => {
    const projectPath = await createFixtureProject({ greeting: "Hello" });
    await addLocale(projectPath, "zh-CN", { greeting: "你好" });
    const overridePath = await addSourcePattern(projectPath, "overrides", {
      locale: "zh-CN",
      messages: {
        greeting: [
          { declarations: ["input name"], match: { "*": "你好 {name}" } },
        ],
      },
    });
    const outputDirectory = await createTemporaryDirectory();

    const result = await generateLanguagePacks({
      projectPath,
      outputDirectory,
    });

    expect(result.undeclaredInputs).toEqual([
      {
        locale: "zh-CN",
        sourcePath: overridePath,
        line: 3,
        column: 3,
        bundleId: "greeting",
        inputs: ["name"],
      },
    ]);
  });

  test("emits descriptive local declarations and formatter nodes", async () => {
    const projectPath = await createFixtureProject({
      item_count: [
        {
          declarations: [
            "input count",
            "local category = count: plural type=cardinal",
          ],
          selectors: ["category"],
          match: {
            "category=one": "{count} item",
            "category=*": "{count} items",
          },
        },
      ],
    });
    const outputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({ projectPath, outputDirectory });

    const pack = JSON.parse(
      await readFile(join(outputDirectory, "en.json"), "utf8"),
    );
    expect(pack.messages.item_count).toEqual({
      declarations: [
        { type: "input", name: "count" },
        {
          type: "local",
          name: "category",
          value: {
            type: "formatter",
            name: "plural",
            argument: { type: "variable", name: "count" },
            options: { type: { type: "literal", value: "cardinal" } },
          },
        },
      ],
      variants: [
        {
          matches: [{ type: "literal", key: "category", value: "one" }],
          pattern: [
            { type: "variable", name: "count" },
            { type: "text", value: " item" },
          ],
        },
        {
          matches: [{ type: "catchall", key: "category" }],
          pattern: [
            { type: "variable", name: "count" },
            { type: "text", value: " items" },
          ],
        },
      ],
    });
  });

  test("produces byte-identical output and preserves unchanged mtimes", async () => {
    const firstOutputDirectory = await createTemporaryDirectory();
    const secondOutputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({
      projectPath: realProjectPath,
      outputDirectory: firstOutputDirectory,
    });
    const facadePath = join(firstOutputDirectory, "messages.ts");
    const packPath = join(firstOutputDirectory, "en.json");
    const before = {
      facade: (await stat(facadePath)).mtimeMs,
      pack: (await stat(packPath)).mtimeMs,
    };

    await generateLanguagePacks({
      projectPath: realProjectPath,
      outputDirectory: firstOutputDirectory,
    });
    await generateLanguagePacks({
      projectPath: realProjectPath,
      outputDirectory: secondOutputDirectory,
    });

    expect((await stat(facadePath)).mtimeMs).toBe(before.facade);
    expect((await stat(packPath)).mtimeMs).toBe(before.pack);
    expect(await readFile(facadePath, "utf8")).toBe(
      await readFile(join(secondOutputDirectory, "messages.ts"), "utf8"),
    );
    expect(await readFile(packPath, "utf8")).toBe(
      await readFile(join(secondOutputDirectory, "en.json"), "utf8"),
    );
  });

  test("removes stale locale packs after a successful compile", async () => {
    const projectPath = await createFixtureProject({ greeting: "Hello" });
    await addLocale(projectPath, "zh-CN", { greeting: "你好" });
    const outputDirectory = await createTemporaryDirectory();
    await generateLanguagePacks({ projectPath, outputDirectory });
    const stalePackPath = join(outputDirectory, "zh-CN.json");

    const settingsPath = join(projectPath, "settings.json");
    const settings = JSON.parse(await readFile(settingsPath, "utf8"));
    settings.locales = ["en"];
    await writeFile(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
    await generateLanguagePacks({
      projectPath,
      outputDirectory,
    });

    await expect(readFile(stalePackPath)).rejects.toMatchObject({
      code: "ENOENT",
    });
    expect(await readdir(outputDirectory)).not.toContain("zh-CN.json");
  });

  test("leaves the previous complete output intact when compilation fails", async () => {
    const projectPath = await createFixtureProject({ greeting: "Hello" });
    const outputDirectory = await createTemporaryDirectory();
    await generateLanguagePacks({ projectPath, outputDirectory });
    const before = await readOutput(outputDirectory);

    await writeCatalog(join(dirname(projectPath), "messages", "en.json"), {
      greeting: "Bad {#link}markup{/link}",
    });
    await expect(
      generateLanguagePacks({ projectPath, outputDirectory }),
    ).rejects.toThrow(/markup-start/);

    expect(await readOutput(outputDirectory)).toEqual(before);
  });

  test.each([
    ["markup", "Bad {#link}markup{/link}", /markup-start/],
    [
      "unknown formatter",
      [
        {
          declarations: ["input count", "local category = count: unsupported"],
          selectors: ["category"],
          match: { "category=*": "{count}" },
        },
      ],
      /formatter "unsupported"/,
    ],
    [
      "unknown declaration",
      [{ declarations: ["mystery value"], match: { "value=*": "bad" } }],
      /Unsupported declaration type/,
    ],
  ])("rejects %s with a positioned error", async (_name, message, detail) => {
    const projectPath = await createFixtureProject({
      invalid_message: message,
    });
    const outputDirectory = await createTemporaryDirectory();

    await expect(
      generateLanguagePacks({ projectPath, outputDirectory }),
    ).rejects.toThrow(
      expect.objectContaining({
        message: expect.stringMatching(
          new RegExp(`messages/en\\.json:3:3.*${detail.source}`),
        ),
      }),
    );
  });

  test("reports untranslated messages per locale without failing the build", async () => {
    const projectPath = await createFixtureProject({
      shared_message: "Shared",
      english_only: "English only",
    });
    await addLocale(projectPath, "zh-CN", { shared_message: "共享" });
    const outputDirectory = await createTemporaryDirectory();

    const result = await generateLanguagePacks({
      projectPath,
      outputDirectory,
    });

    const pack = JSON.parse(
      await readFile(join(outputDirectory, "zh-CN.json"), "utf8"),
    );
    expect(pack.messages).not.toHaveProperty("english_only");
    expect(result.untranslated).toEqual([
      {
        locale: "zh-CN",
        sourcePath: join(dirname(projectPath), "messages", "zh-CN.json"),
        sourcePaths: [join(dirname(projectPath), "messages", "zh-CN.json")],
        bundleIds: ["english_only"],
      },
    ]);
    expect(formatCompilerWarnings(result)).toMatch(
      /zh-CN\.json: 1 untranslated message\(s\).*english_only/,
    );
    expect(
      formatCompilerWarnings({
        untranslated: [],
        undeclaredInputs: [],
        missingBaseLocale: undefined,
      }),
    ).toBeUndefined();
  });

  test("omits a bundle with no base-locale message from every artifact", async () => {
    const projectPath = await createFixtureProject({
      shared_message: "Shared",
    });
    await addLocale(projectPath, "zh-CN", {
      shared_message: "共享",
      chinese_only: "仅中文",
    });
    const outputDirectory = await createTemporaryDirectory();

    const result = await generateLanguagePacks({
      projectPath,
      outputDirectory,
    });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    const chinesePack = await readFile(
      join(outputDirectory, "zh-CN.json"),
      "utf8",
    );
    expect(facade).not.toContain("chinese_only");
    expect(chinesePack).not.toContain("chinese_only");
    expect(result.untranslated).toEqual([]);
    expect(result.missingBaseLocale).toEqual({
      sourcePath: join(dirname(projectPath), "messages", "en.json"),
      sourcePaths: [join(dirname(projectPath), "messages", "en.json")],
      bundleIds: ["chinese_only"],
    });
    expect(formatCompilerWarnings(result)).toMatch(
      /en\.json: 1 message\(s\) absent from the base locale.*chinese_only/,
    );
  });

  test("types inputs from base-locale formatter and selector usage", async () => {
    const projectPath = await createFixtureProject({
      typed_inputs: [
        {
          declarations: [
            "input count",
            "input amount",
            "input when",
            "input label",
            "local category = count: plural",
            "local formatted = amount: number",
            "local day = when: datetime",
          ],
          selectors: ["category"],
          match: {
            "category=one": "{label} {formatted} {day}",
            "category=*": "{label} {formatted} {day}",
          },
        },
      ],
      conflicting_input: [
        {
          declarations: [
            "input value",
            "local counted = value: number",
            "local dated = value: datetime",
          ],
          match: { "*": "{counted} {dated}" },
        },
      ],
      numeric_selector: [
        {
          declarations: ["input count"],
          selectors: ["count"],
          match: { "count=1": "one", "count=*": "many" },
        },
      ],
    });
    const outputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({ projectPath, outputDirectory });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    expect(facade).toContain(
      'import { type DatetimeInput } from "@zotlit/obsidian-i18n";',
    );
    expect(facade).toContain(
      "export const typed_inputs = (inputs: { count: number; amount: number; when: DatetimeInput; label: string | number }): string",
    );
    expect(facade).toContain(
      "export const conflicting_input = (inputs: { value: string | number }): string",
    );
    expect(facade).toContain(
      "export const numeric_selector = (inputs: { count: number }): string",
    );
  });

  test("does not type a selector matching an unsafe-integer literal as a number", async () => {
    const projectPath = await createFixtureProject({
      unsafe_numeric_selector: [
        {
          declarations: ["input count"],
          selectors: ["count"],
          match: { "count=9007199254740993": "one", "count=*": "many" },
        },
      ],
    });
    const outputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({ projectPath, outputDirectory });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    // "9007199254740993" is not a safe integer, so it behaves as a plain
    // string literal consistently with the runtime's selector matching.
    expect(facade).toContain(
      "export const unsafe_numeric_selector = (inputs: { count: string | number }): string",
    );
  });

  test("ignores input narrowing a non-base locale introduces", async () => {
    const projectPath = await createFixtureProject({
      item_count: [
        { declarations: ["input count"], match: { "*": "{count} items" } },
      ],
    });
    await addLocale(projectPath, "zh-CN", {
      item_count: [
        {
          declarations: ["input count", "local formatted = count: number"],
          match: { "*": "{formatted} 项" },
        },
      ],
    });
    const outputDirectory = await createTemporaryDirectory();

    const result = await generateLanguagePacks({
      projectPath,
      outputDirectory,
    });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    const chinesePack = JSON.parse(
      await readFile(join(outputDirectory, "zh-CN.json"), "utf8"),
    );
    expect(facade).toContain(
      "export const item_count = (inputs: { count: string | number }): string",
    );
    expect(chinesePack.messages.item_count.declarations).toEqual([
      { type: "input", name: "count" },
      {
        type: "local",
        name: "formatted",
        value: {
          type: "formatter",
          name: "number",
          argument: { type: "variable", name: "count" },
          options: {},
        },
      },
    ]);
    expect(result.undeclaredInputs).toEqual([]);
  });

  test("drops and reports a locale message using an undeclared input", async () => {
    const projectPath = await createFixtureProject({
      greeting: "Hello",
      farewell: "Goodbye",
    });
    await addLocale(projectPath, "zh-CN", {
      greeting: [
        { declarations: ["input name"], match: { "*": "你好 {name}" } },
      ],
      farewell: "再见",
    });
    const outputDirectory = await createTemporaryDirectory();

    const result = await generateLanguagePacks({
      projectPath,
      outputDirectory,
    });

    const facade = await readFile(join(outputDirectory, "messages.ts"), "utf8");
    const chinesePack = JSON.parse(
      await readFile(join(outputDirectory, "zh-CN.json"), "utf8"),
    );
    expect(facade).toContain("export const greeting = (): string");
    expect(chinesePack.messages).toEqual({ farewell: "再见" });
    expect(result.undeclaredInputs).toEqual([
      {
        locale: "zh-CN",
        sourcePath: join(dirname(projectPath), "messages", "zh-CN.json"),
        line: 3,
        column: 3,
        bundleId: "greeting",
        inputs: ["name"],
      },
    ]);
    expect(result.untranslated).toEqual([]);
    expect(formatCompilerWarnings(result)).toMatch(
      /zh-CN\.json:3:3: "greeting" uses input\(s\) the base locale does not declare \(name\)/,
    );
  });

  test("carries only the declarations each locale message references", async () => {
    const projectPath = await createFixtureProject({
      item_count: [
        { declarations: ["input count"], match: { "*": "{count} items" } },
      ],
      item_range: [
        {
          declarations: ["input shown", "input total"],
          match: { "*": "{shown} of {total}" },
        },
      ],
    });
    await addLocale(projectPath, "zh-CN", {
      item_count: "很多项",
      item_range: [
        { declarations: ["input shown"], match: { "*": "共 {shown}" } },
      ],
    });
    const outputDirectory = await createTemporaryDirectory();

    await generateLanguagePacks({ projectPath, outputDirectory });

    const basePack = JSON.parse(
      await readFile(join(outputDirectory, "en.json"), "utf8"),
    );
    const chinesePack = JSON.parse(
      await readFile(join(outputDirectory, "zh-CN.json"), "utf8"),
    );
    // A translation without placeholders collapses even though the base
    // Message takes an input.
    expect(chinesePack.messages.item_count).toBe("很多项");
    expect(basePack.messages.item_count.declarations).toEqual([
      { type: "input", name: "count" },
    ]);
    // A translation using fewer inputs carries only the ones it references.
    expect(chinesePack.messages.item_range.declarations).toEqual([
      { type: "input", name: "shown" },
    ]);
    expect(basePack.messages.item_range.declarations).toEqual([
      { type: "input", name: "shown" },
      { type: "input", name: "total" },
    ]);
  });

  test("rejects a name two locales declare differently", async () => {
    const declaring = (annotation: string): unknown => [
      {
        declarations: ["input value", `local shown = value: ${annotation}`],
        match: { "*": "{shown}" },
      },
    ];
    const projectPath = await createFixtureProject({
      shown_value: declaring("number"),
    });
    await addLocale(projectPath, "zh-CN", {
      shown_value: declaring("datetime"),
    });
    const outputDirectory = await createTemporaryDirectory();

    await expect(
      generateLanguagePacks({ projectPath, outputDirectory }),
    ).rejects.toThrow(/redeclared "shown" in message "shown_value"/);
  });

  test("rejects an input name that is not an identifier", async () => {
    const projectPath = await createFixtureProject({
      annotated_placeholder: [
        {
          declarations: ["input amount"],
          match: { "*": "{amount :number}" },
        },
      ],
    });
    const outputDirectory = await createTemporaryDirectory();

    await expect(
      generateLanguagePacks({ projectPath, outputDirectory }),
    ).rejects.toThrow(/input name "amount :number"/);
  });

  test("positions markup errors in the locale source catalog", async () => {
    const projectPath = await createFixtureProject({
      valid_message: "Valid",
    });
    await addLocale(projectPath, "zh-CN", {
      invalid_message: "Bad {#link}markup{/link}",
    });
    const outputDirectory = await createTemporaryDirectory();

    await expect(
      generateLanguagePacks({ projectPath, outputDirectory }),
    ).rejects.toThrow(
      expect.objectContaining({
        message: expect.stringMatching(
          /messages\/zh-CN\.json:3:3.*markup-start/,
        ),
      }),
    );
  });

  test("positions project errors in a discovered custom source catalog", async () => {
    const projectPath = await createFixtureProject({
      invalid_message: "Valid",
    });
    const sourcePath = await addSourcePattern(projectPath, "custom", {
      messages: {
        invalid_message: [
          {
            declarations: ["mystery value"],
            match: { "value=*": "bad" },
          },
        ],
      },
    });
    const outputDirectory = await createTemporaryDirectory();

    await expect(
      generateLanguagePacks({ projectPath, outputDirectory }),
    ).rejects.toThrow(
      expect.objectContaining({
        message: expect.stringContaining(`${sourcePath}:3:3`),
      }),
    );
  });

  test("rejects reserved words before emitting invalid TypeScript", async () => {
    const projectPath = await createFixtureProject({ class: "Invalid" });
    const outputDirectory = await createTemporaryDirectory();

    await expect(
      generateLanguagePacks({ projectPath, outputDirectory }),
    ).rejects.toThrow('Unsupported bundle ID "class"');
  });

  test.each([
    [
      "schema version",
      languagePack({ schemaVersion: 2 }),
      "schemaVersion must be 1",
    ],
    ["locale", languagePack({ locale: "fr" }), 'locale must equal "zh-CN"'],
    [
      "structure",
      languagePack({ messages: { bad: { declarations: [] } } }),
      "variants is required",
    ],
    [
      "total size",
      languagePack({
        messages: Object.fromEntries(
          Array.from({ length: 30 }, (_, index) => [
            `message_${index}`,
            "文".repeat(9_000),
          ]),
        ),
      }),
      "exceeds 262144 bytes",
    ],
    [
      "message count",
      languagePack({
        messages: Object.fromEntries(
          Array.from({ length: 1_001 }, (_, index) => [`message_${index}`, ""]),
        ),
      }),
      "exceeds 1000 messages",
    ],
    [
      "text length",
      languagePack({ messages: { long: "x".repeat(10_001) } }),
      "exceeds 10000 characters",
    ],
    [
      "nesting depth",
      languagePack({
        messages: { deep: structuredMessage(nestedFormatter(12)) },
      }),
      "exceeds nesting depth 16",
    ],
    [
      "formatter allowlist",
      languagePack({
        messages: {
          unsafe: structuredMessage({
            type: "formatter",
            name: "execute",
            argument: { type: "variable", name: "value" },
            options: {},
          }),
        },
      }),
      'unsupported formatter "execute"',
    ],
  ])("rejects a pack with invalid %s", (_name, pack, detail) => {
    expect(() =>
      validateLanguagePack(JSON.stringify(pack), {
        expectedLocale: "zh-CN",
      }),
    ).toThrow(detail);
  });

  test.each([
    ["newer", 2, true],
    ["older", 0, false],
    ["non-numeric", "1", false],
  ])(
    "flags a %s schema version as updateNeeded=%s",
    (_name, schemaVersion, updateNeeded) => {
      const reject = (): unknown =>
        validateLanguagePack(JSON.stringify(languagePack({ schemaVersion })), {
          expectedLocale: "zh-CN",
        });

      expect(reject).toThrow(LanguagePackSchemaVersionError);
      expect(reject).toThrow(
        expect.objectContaining({ updateNeeded }) as Error,
      );
    },
  );
});

function languagePack(
  overrides: Record<string, unknown> = {},
): Record<string, unknown> {
  return {
    schemaVersion: 1,
    locale: "zh-CN",
    messages: { greeting: "你好" },
    ...overrides,
  };
}

function structuredMessage(expression: unknown): Record<string, unknown> {
  return {
    declarations: [{ type: "input", name: "value" }],
    variants: [{ matches: [], pattern: [expression] }],
  };
}

function nestedFormatter(depth: number): Record<string, unknown> {
  return depth === 0
    ? { type: "variable", name: "value" }
    : {
        type: "formatter",
        name: "number",
        argument: nestedFormatter(depth - 1),
        options: {},
      };
}

async function readOutput(
  outputDirectory: string,
): Promise<Record<string, string>> {
  return Object.fromEntries(
    await Promise.all(
      (await readdir(outputDirectory))
        .sort()
        .map(async (fileName) => [
          fileName,
          await readFile(join(outputDirectory, fileName), "utf8"),
        ]),
    ),
  );
}

async function typecheckGeneratedOutput(
  outputDirectory: string,
  { include = [] }: { include?: readonly string[] } = {},
): Promise<void> {
  const configPath = join(outputDirectory, "tsconfig.json");
  // The emitted catalog is a bare object literal, so compiling it alone proves
  // nothing. This binds it to the type the lifecycle consumes it as.
  await writeFile(
    join(outputDirectory, "locale-catalog-check.ts"),
    [
      `import { type LocaleCatalog } from "@zotlit/obsidian-i18n";`,
      ``,
      `import { catalog } from "./catalog.js";`,
      ``,
      `export const localeCatalog: LocaleCatalog = catalog;`,
      ``,
    ].join("\n"),
  );
  await writeFile(
    configPath,
    `${JSON.stringify(
      {
        compilerOptions: {
          strict: true,
          noEmit: true,
          skipLibCheck: true,
          module: "preserve",
          moduleResolution: "bundler",
          target: "ES2025",
          resolveJsonModule: true,
          paths: {
            "@zotlit/obsidian-i18n": [
              resolve(import.meta.dirname, "..", "dist", "index.d.mts"),
            ],
          },
        },
        include: [
          "messages.ts",
          "runtime.ts",
          "catalog.ts",
          "locale-catalog-check.ts",
          ...include,
        ],
      },
      null,
      2,
    )}\n`,
  );
  try {
    await execFileAsync(process.execPath, [
      resolve(
        import.meta.dirname,
        "..",
        "node_modules",
        "typescript",
        "bin",
        "tsc",
      ),
      "--project",
      configPath,
    ]);
  } catch (error) {
    const processError = error as Error & {
      stdout?: string;
      stderr?: string;
    };
    throw new Error(
      [processError.message, processError.stdout, processError.stderr]
        .filter(Boolean)
        .join("\n"),
      { cause: error },
    );
  }
}

async function generateLanguagePacks(options: {
  projectPath: string;
  outputDirectory: string;
  targetLocaleMessagePrefixes?: readonly string[];
}): Promise<CompileResult> {
  return compile({
    root: dirname(options.projectPath),
    project: options.projectPath,
    output: options.outputDirectory,
    excludeMessagePrefixes: ["docs_"],
    targetLocaleMessagePrefixes: options.targetLocaleMessagePrefixes,
  });
}

/**
 * Loads the emitted modules as a consumer's bundler would, so a test asserts
 * what the wrappers render rather than what the generator wrote. Requires a
 * compile with configured target-locale prefixes, which emits the subsets.
 */
async function loadGeneratedModules<Messages = Record<string, never>>(
  outputDirectory: string,
): Promise<{
  runtime: LanguagePackRuntime;
  messages: Messages;
  targetLocaleMessages: TargetLocaleMessages;
  [Symbol.asyncDispose](): Promise<void>;
}> {
  const server = await createServer({
    root: outputDirectory,
    logLevel: "silent",
    appType: "custom",
    resolve: {
      alias: {
        "@zotlit/obsidian-i18n": fileURLToPath(
          import.meta.resolve("@zotlit/obsidian-i18n"),
        ),
      },
    },
    server: { middlewareMode: true },
  });
  const { runtime } = (await server.ssrLoadModule("/runtime.ts")) as {
    runtime: LanguagePackRuntime;
  };
  const messages = (await server.ssrLoadModule("/messages.ts")) as Messages;
  const { targetLocaleMessages } = (await server.ssrLoadModule(
    "/target-locale-messages.ts",
  )) as { targetLocaleMessages: TargetLocaleMessages };
  return {
    runtime,
    messages,
    targetLocaleMessages,
    [Symbol.asyncDispose]: () => server.close(),
  };
}
