import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { glob } from "tinyglobby";
import type { Plugin } from "vite";

import { parsePrefsFile } from "./parse-prefs.js";

export interface PrefsPluginOpts {
  root: string;
  /** Required pref-key prefix, e.g. `"extensions.zotlit."`. Build fails if any key misses it. */
  prefix: string;
  /** Path to the `pref(...)` defaults file, relative to `root`. */
  prefsFile: string;
  /** Addon-staging source dir; every `.xhtml` underneath is scanned for `preference="..."` refs. */
  addonDir: string;
  /** Codegen output path for the `PluginPrefKey` union, relative to `root`. */
  typesOutput: string;
}

const PREFERENCE_RE = /\bpreference="([^"]+)"/g;

function emitTypesFile(keys: ReadonlyArray<string>): string {
  const sorted = [...keys].sort();
  const banner =
    "// GENERATED by scripts/vite-prefs-plugin.ts — DO NOT EDIT.\n" +
    "// Source of truth: addon/prefs.js\n";
  const union =
    sorted.length === 0
      ? "  never"
      : sorted.map((k) => `  | "${k}"`).join("\n");
  return `${banner}\nexport type PluginPrefKey =\n${union};\n`;
}

function extractPreferenceRefs(text: string): string[] {
  const out: string[] = [];
  for (const m of text.matchAll(PREFERENCE_RE)) out.push(m[1]!);
  return out;
}

export function prefsPlugin({
  root,
  prefix,
  prefsFile,
  addonDir,
  typesOutput,
}: PrefsPluginOpts): Plugin {
  const absPrefsFile = resolve(root, prefsFile);
  const absAddonDir = resolve(root, addonDir);
  const absTypesOutput = resolve(root, typesOutput);
  const prefsFileRel = relative(root, absPrefsFile);

  return {
    name: "zotero-prefs",
    async buildStart() {
      const source = await readFile(absPrefsFile, "utf-8");
      const { entries, errors: parseErrors } = parsePrefsFile(
        source,
        absPrefsFile,
        prefsFileRel,
      );
      const errors: string[] = [...parseErrors];

      for (const { key, line } of entries) {
        if (!key.startsWith(prefix)) {
          errors.push(
            `  ${prefsFileRel}:${line}: pref key "${key}" missing prefix "${prefix}"`,
          );
        }
      }

      const seen = new Map<string, number>();
      for (const { key, line } of entries) {
        const prev = seen.get(key);
        if (prev !== undefined) {
          errors.push(
            `  ${prefsFileRel}:${line}: duplicate pref key "${key}" (first at line ${prev})`,
          );
        } else {
          seen.set(key, line);
        }
      }

      const declaredKeys = new Set(entries.map((e) => e.key));

      const xhtmlPaths = await glob("**/*.xhtml", {
        cwd: absAddonDir,
        absolute: true,
      });
      for (const xhtmlPath of xhtmlPaths) {
        const text = await readFile(xhtmlPath, "utf-8");
        for (const ref of extractPreferenceRefs(text)) {
          if (!declaredKeys.has(ref)) {
            errors.push(
              `  ${relative(root, xhtmlPath)}: preference="${ref}" not declared in ${prefsFileRel}`,
            );
          }
        }
      }

      if (errors.length > 0) {
        this.error(`[prefs] validation failed:\n${errors.join("\n")}`);
      }

      const expectedTypes = emitTypesFile([...declaredKeys]);
      let onDiskTypes: string | null = null;
      try {
        onDiskTypes = await readFile(absTypesOutput, "utf-8");
      } catch {
        // file missing — write below
      }
      if (onDiskTypes !== expectedTypes) {
        await mkdir(dirname(absTypesOutput), { recursive: true });
        await writeFile(absTypesOutput, expectedTypes);
        if (!this.meta.watchMode) {
          this.error(
            `[prefs] ${typesOutput} was out of sync with ${prefsFileRel} — regenerated. ` +
              `Commit the change and rerun the build.`,
          );
        }
      }

      this.addWatchFile(absPrefsFile);
      this.addWatchFile(absAddonDir);
      for (const p of xhtmlPaths) this.addWatchFile(p);
    },
  };
}
