import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";

import { parse, type Resource } from "@fluent/syntax";
import { glob } from "tinyglobby";
import type { Plugin } from "vite";

import type { ZoteroBuildEnv } from "./vite-zotero-plugin.js";

export interface FluentPluginOpts {
  root: string;
  env: ZoteroBuildEnv;
  /** Required FTL id prefix, e.g. `"zotlit"`. Build fails if any id misses it. */
  prefix: string;
  /** Authored FTL dir, flat (`locale/{locale}.ftl`), relative to `root`. */
  localeDir: string;
  /** Filename Zotero resolves via `new Localization([ftlFileName])`. */
  ftlFileName: string;
  /** Addon-staging source dir; every `.xhtml` underneath is scanned for `data-l10n-id` refs. */
  addonDir: string;
  /** Codegen output path for the `FluentMessageId` union, relative to `root`. */
  typesOutput: string;
  /** Locale that defines `FluentMessageId`; other locales are checked against it. */
  primaryLocale: string;
}

interface LocaleFtl {
  locale: string;
  sourcePath: string;
  text: string;
  ids: Set<string>;
}

const DATA_L10N_RE = /\bdata-l10n-id="([^"]+)"/g;

async function readLocales(absLocaleDir: string): Promise<LocaleFtl[]> {
  const ftlPaths = await glob("*.ftl", {
    cwd: absLocaleDir,
    absolute: true,
  });
  const out: LocaleFtl[] = [];
  for (const sourcePath of ftlPaths) {
    const text = await readFile(sourcePath, "utf-8");
    const resource: Resource = parse(text, { withSpans: false });
    const ids = new Set<string>();
    for (const entry of resource.body) {
      if (entry.type === "Message" || entry.type === "Term") {
        ids.add(entry.id.name);
      }
    }
    out.push({
      locale: basename(sourcePath, ".ftl"),
      sourcePath,
      text,
      ids,
    });
  }
  return out;
}

function emitTypesFile(ids: ReadonlyArray<string>): string {
  const sorted = [...ids].sort();
  const banner =
    "// GENERATED by scripts/vite-fluent-plugin.ts — DO NOT EDIT.\n" +
    "// Source of truth: locale/*.ftl\n";
  const union =
    sorted.length === 0
      ? "  | never"
      : sorted.map((id) => `  | "${id}"`).join("\n");
  return `${banner}\nexport type FluentMessageId =\n${union};\n`;
}

function extractDataL10nIds(text: string): string[] {
  const out: string[] = [];
  for (const m of text.matchAll(DATA_L10N_RE)) out.push(m[1]!);
  return out;
}

export function fluentPlugin({
  root,
  env,
  prefix,
  localeDir,
  ftlFileName,
  addonDir,
  typesOutput,
  primaryLocale,
}: FluentPluginOpts): Plugin {
  const absLocaleDir = resolve(root, localeDir);
  const absAddonDir = resolve(root, addonDir);
  const absTypesOutput = resolve(root, typesOutput);
  const absStaging = resolve(root, env.addonStaging);
  const expectedPrefix = `${prefix}-`;

  let locales: LocaleFtl[] = [];

  return {
    name: "zotero-fluent",
    async buildStart() {
      locales = await readLocales(absLocaleDir);
      if (locales.length === 0) {
        this.error(`[fluent] no .ftl files in ${localeDir}/`);
      }
      const primary = locales.find((l) => l.locale === primaryLocale);
      if (!primary) {
        this.error(
          `[fluent] primary locale "${primaryLocale}" not found in ${localeDir}/. ` +
            `Available: ${locales.map((l) => l.locale).join(", ")}`,
        );
      }

      const errors: string[] = [];

      for (const l of locales) {
        for (const id of l.ids) {
          if (!id.startsWith(expectedPrefix)) {
            errors.push(
              `  ${relative(root, l.sourcePath)}: id "${id}" missing prefix "${expectedPrefix}"`,
            );
          }
        }
      }

      const primaryIds = primary.ids;
      const xhtmlPaths = await glob("**/*.xhtml", {
        cwd: absAddonDir,
        absolute: true,
      });
      for (const xhtmlPath of xhtmlPaths) {
        const text = await readFile(xhtmlPath, "utf-8");
        for (const ref of extractDataL10nIds(text)) {
          if (!primaryIds.has(ref)) {
            errors.push(
              `  ${relative(root, xhtmlPath)}: data-l10n-id="${ref}" not declared in ${localeDir}/${primaryLocale}.ftl`,
            );
          }
        }
      }

      if (errors.length > 0) {
        this.error(`[fluent] validation failed:\n${errors.join("\n")}`);
      }

      for (const l of locales) {
        if (l.locale === primaryLocale) continue;
        const missing: string[] = [];
        const extra: string[] = [];
        for (const id of primaryIds) if (!l.ids.has(id)) missing.push(id);
        for (const id of l.ids) if (!primaryIds.has(id)) extra.push(id);
        if (missing.length || extra.length) {
          const missingPart = missing.length
            ? ` missing [${missing.join(", ")}]`
            : "";
          const extraPart = extra.length ? ` extra [${extra.join(", ")}]` : "";
          this.warn(
            `[fluent] ${l.locale} drift vs ${primaryLocale}:${missingPart}${extraPart}`,
          );
        }
      }

      const expectedTypes = emitTypesFile([...primaryIds]);
      let onDiskTypes: string | null = null;
      try {
        onDiskTypes = await readFile(absTypesOutput, "utf-8");
      } catch {
        // file missing — write below
      }
      if (onDiskTypes !== expectedTypes) {
        await mkdir(dirname(absTypesOutput), { recursive: true });
        await writeFile(absTypesOutput, expectedTypes);
        if (!this.meta.watchMode) {
          this.error(
            `[fluent] ${typesOutput} was out of sync with FTL — regenerated. ` +
              `Commit the change and rerun the build.`,
          );
        }
      }

      this.addWatchFile(absLocaleDir);
      for (const l of locales) this.addWatchFile(l.sourcePath);
      this.addWatchFile(absAddonDir);
      for (const p of xhtmlPaths) this.addWatchFile(p);
    },
    async writeBundle() {
      for (const l of locales) {
        const outDir = join(absStaging, "locale", l.locale);
        await mkdir(outDir, { recursive: true });
        await writeFile(join(outDir, ftlFileName), l.text);
      }
    },
  };
}
